/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#ifndef WebCore_bindings_scripts_test_JS_JSTestStandaloneDictionary_h
#define WebCore_bindings_scripts_test_JS_JSTestStandaloneDictionary_h

#if ENABLE(Condition1)

#include "DictionaryImplName.h"
#include "JSDOMConvertDictionary.h"
#include "JSDOMConvertEnumeration.h"

namespace WebCore {

template<> WEBCORE_EXPORT ConversionResult<IDLDictionary<DictionaryImplName>> convertDictionary<DictionaryImplName>(JSC::JSGlobalObject&, JSC::JSValue);

WEBCORE_EXPORT JSC::JSObject* convertDictionaryToJS(JSC::JSGlobalObject&, JSDOMGlobalObject&, const DictionaryImplName&);

String convertEnumerationToString(TestStandaloneDictionary::EnumInStandaloneDictionaryFile);
template<> JSC::JSString* convertEnumerationToJS(JSC::VM&, TestStandaloneDictionary::EnumInStandaloneDictionaryFile);

template<> std::optional<TestStandaloneDictionary::EnumInStandaloneDictionaryFile> parseEnumerationFromString<TestStandaloneDictionary::EnumInStandaloneDictionaryFile>(const String&);
template<> std::optional<TestStandaloneDictionary::EnumInStandaloneDictionaryFile> parseEnumeration<TestStandaloneDictionary::EnumInStandaloneDictionaryFile>(JSC::JSGlobalObject&, JSC::JSValue);
template<> ASCIILiteral expectedEnumerationValues<TestStandaloneDictionary::EnumInStandaloneDictionaryFile>();

} // namespace WebCore

#endif // ENABLE(Condition1)
#endif // WebCore_bindings_scripts_test_JS_JSTestStandaloneDictionary_h
