/* Copyright (C) 2020 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1.  Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 * 2.  Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// This file is generated by generate-gpup-webgl. Do not edit.
// This file should be included in the private section of the
// RemoteGraphicsContextGL implementations.
#pragma once
    void activeTexture(WTF::CheckedUint32 texture);
    void attachShader(WTF::CheckedUint32 program, WTF::CheckedUint32 shader);
    void bindAttribLocation(WTF::CheckedUint32 arg0, WTF::CheckedUint32 index, CString&& name);
    void bindBuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1);
    void bindFramebuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1);
    void bindRenderbuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1);
    void bindTexture(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1);
    void blendColor(float red, float green, float blue, float alpha);
    void blendEquation(WTF::CheckedUint32 mode);
    void blendEquationSeparate(WTF::CheckedUint32 modeRGB, WTF::CheckedUint32 modeAlpha);
    void blendFunc(WTF::CheckedUint32 sfactor, WTF::CheckedUint32 dfactor);
    void blendFuncSeparate(WTF::CheckedUint32 srcRGB, WTF::CheckedUint32 dstRGB, WTF::CheckedUint32 srcAlpha, WTF::CheckedUint32 dstAlpha);
    void checkFramebufferStatus(WTF::CheckedUint32 target, CompletionHandler<void(uint32_t)>&&);
    void clear(WTF::CheckedUint32 mask);
    void clearColor(float red, float green, float blue, float alpha);
    void clearDepth(float depth);
    void clearStencil(WTF::CheckedInt32 s);
    void colorMask(bool red, bool green, bool blue, bool alpha);
    void compileShader(WTF::CheckedUint32 arg0);
    void copyTexImage2D(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border);
    void copyTexSubImage2D(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void createBuffer(WTF::CheckedUint32 name);
    void createFramebuffer(WTF::CheckedUint32 name);
    void createProgram(WTF::CheckedUint32 name);
    void createRenderbuffer(WTF::CheckedUint32 name);
    void createShader(WTF::CheckedUint32 name, WTF::CheckedUint32 arg0);
    void createTexture(WTF::CheckedUint32 name);
    void cullFace(WTF::CheckedUint32 mode);
    void deleteBuffer(WTF::CheckedUint32 arg0);
    void deleteFramebuffer(WTF::CheckedUint32 arg0);
    void deleteProgram(WTF::CheckedUint32 arg0);
    void deleteRenderbuffer(WTF::CheckedUint32 arg0);
    void deleteShader(WTF::CheckedUint32 arg0);
    void deleteTexture(WTF::CheckedUint32 arg0);
    void depthFunc(WTF::CheckedUint32 func);
    void depthMask(bool flag);
    void depthRange(float zNear, float zFar);
    void detachShader(WTF::CheckedUint32 arg0, WTF::CheckedUint32 arg1);
    void disable(WTF::CheckedUint32 cap);
    void disableVertexAttribArray(WTF::CheckedUint32 index);
    void drawArrays(WTF::CheckedUint32 mode, WTF::CheckedInt32 first, WTF::CheckedInt32 count);
    void drawElements(WTF::CheckedUint32 mode, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset);
    void enable(WTF::CheckedUint32 cap);
    void enableVertexAttribArray(WTF::CheckedUint32 index);
    void finish();
    void flush();
    void framebufferRenderbuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 renderbuffertarget, WTF::CheckedUint32 arg3);
    void framebufferTexture2D(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 textarget, WTF::CheckedUint32 arg3, WTF::CheckedInt32 level);
    void frontFace(WTF::CheckedUint32 mode);
    void generateMipmap(WTF::CheckedUint32 target);
    void activeAttribs(WTF::CheckedUint32 program, CompletionHandler<void(Vector<WebCore::GCGLAttribActiveInfo>&&)>&&);
    void activeUniforms(WTF::CheckedUint32 program, CompletionHandler<void(Vector<WebCore::GCGLUniformActiveInfo>&&)>&&);
    void getBufferParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getString(WTF::CheckedUint32 name, CompletionHandler<void(CString&&)>&&);
    void getFloatv(WTF::CheckedUint32 pname, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const float>)>&&);
    void getIntegerv(WTF::CheckedUint32 pname, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const int32_t>)>&&);
    void getIntegeri_v(WTF::CheckedUint32 pname, WTF::CheckedUint32 index, CompletionHandler<void(std::span<const int32_t, 4>)>&&); // NOLINT
    void getInteger64(WTF::CheckedUint32 pname, CompletionHandler<void(int64_t)>&&);
    void getInteger64i(WTF::CheckedUint32 pname, WTF::CheckedUint32 index, CompletionHandler<void(int64_t)>&&);
    void getProgrami(WTF::CheckedUint32 program, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getBooleanv(WTF::CheckedUint32 pname, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const bool>)>&&);
    void getFramebufferAttachmentParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getProgramInfoLog(WTF::CheckedUint32 arg0, CompletionHandler<void(CString&&)>&&);
    void getRenderbufferParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getShaderi(WTF::CheckedUint32 arg0, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getShaderInfoLog(WTF::CheckedUint32 arg0, CompletionHandler<void(CString&&)>&&);
    void getShaderPrecisionFormat(WTF::CheckedUint32 shaderType, WTF::CheckedUint32 precisionType, CompletionHandler<void(std::span<const int32_t, 2>, int32_t)>&&);
    void getTexParameterf(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(float)>&&);
    void getTexParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getUniformfv(WTF::CheckedUint32 program, WTF::CheckedInt32 location, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const float>)>&&);
    void getUniformiv(WTF::CheckedUint32 program, WTF::CheckedInt32 location, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const int32_t>)>&&);
    void getUniformuiv(WTF::CheckedUint32 program, WTF::CheckedInt32 location, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const uint32_t>)>&&);
    void getVertexAttribOffset(WTF::CheckedUint32 index, WTF::CheckedUint32 pname, CompletionHandler<void(uint64_t)>&&);
    void hint(WTF::CheckedUint32 target, WTF::CheckedUint32 mode);
    void isBuffer(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isEnabled(WTF::CheckedUint32 cap, CompletionHandler<void(bool)>&&);
    void isFramebuffer(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isProgram(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isRenderbuffer(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isShader(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isTexture(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void lineWidth(float arg0);
    void linkProgram(WTF::CheckedUint32 arg0);
    void pixelStorei(WTF::CheckedUint32 pname, WTF::CheckedInt32 param);
    void polygonOffset(float factor, float units);
    void renderbufferStorage(WTF::CheckedUint32 target, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void sampleCoverage(float value, bool invert);
    void scissor(WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void shaderSource(WTF::CheckedUint32 arg0, CString&& arg1);
    void stencilFunc(WTF::CheckedUint32 func, WTF::CheckedInt32 ref, WTF::CheckedUint32 mask);
    void stencilFuncSeparate(WTF::CheckedUint32 face, WTF::CheckedUint32 func, WTF::CheckedInt32 ref, WTF::CheckedUint32 mask);
    void stencilMask(WTF::CheckedUint32 mask);
    void stencilMaskSeparate(WTF::CheckedUint32 face, WTF::CheckedUint32 mask);
    void stencilOp(WTF::CheckedUint32 fail, WTF::CheckedUint32 zfail, WTF::CheckedUint32 zpass);
    void stencilOpSeparate(WTF::CheckedUint32 face, WTF::CheckedUint32 fail, WTF::CheckedUint32 zfail, WTF::CheckedUint32 zpass);
    void texParameterf(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, float param);
    void texParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, WTF::CheckedInt32 param);
    void uniform1f(WTF::CheckedInt32 location, float x);
    void uniform1fv(WTF::CheckedInt32 location, std::span<const float>&& v);
    void uniform1i(WTF::CheckedInt32 location, WTF::CheckedInt32 x);
    void uniform1iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v);
    void uniform2f(WTF::CheckedInt32 location, float x, float y);
    void uniform2fv(WTF::CheckedInt32 location, std::span<const float>&& v);
    void uniform2i(WTF::CheckedInt32 location, WTF::CheckedInt32 x, WTF::CheckedInt32 y);
    void uniform2iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v);
    void uniform3f(WTF::CheckedInt32 location, float x, float y, float z);
    void uniform3fv(WTF::CheckedInt32 location, std::span<const float>&& v);
    void uniform3i(WTF::CheckedInt32 location, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 z);
    void uniform3iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v);
    void uniform4f(WTF::CheckedInt32 location, float x, float y, float z, float w);
    void uniform4fv(WTF::CheckedInt32 location, std::span<const float>&& v);
    void uniform4i(WTF::CheckedInt32 location, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 z, WTF::CheckedInt32 w);
    void uniform4iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v);
    void uniformMatrix2fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& value);
    void uniformMatrix3fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& value);
    void uniformMatrix4fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& value);
    void useProgram(WTF::CheckedUint32 arg0);
    void validateProgram(WTF::CheckedUint32 arg0);
    void vertexAttrib1f(WTF::CheckedUint32 index, float x);
    void vertexAttrib1fv(WTF::CheckedUint32 index, std::span<const float, 1>&& values);
    void vertexAttrib2f(WTF::CheckedUint32 index, float x, float y);
    void vertexAttrib2fv(WTF::CheckedUint32 index, std::span<const float, 2>&& values);
    void vertexAttrib3f(WTF::CheckedUint32 index, float x, float y, float z);
    void vertexAttrib3fv(WTF::CheckedUint32 index, std::span<const float, 3>&& values);
    void vertexAttrib4f(WTF::CheckedUint32 index, float x, float y, float z, float w);
    void vertexAttrib4fv(WTF::CheckedUint32 index, std::span<const float, 4>&& values);
    void vertexAttribPointer(WTF::CheckedUint32 index, WTF::CheckedInt32 size, WTF::CheckedUint32 type, bool normalized, WTF::CheckedInt32 stride, WTF::CheckedUint64 offset);
    void viewport(WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void bufferData0(WTF::CheckedUint32 target, WTF::CheckedUint64 arg1, WTF::CheckedUint32 usage);
    void bufferData1(WTF::CheckedUint32 target, std::span<const uint8_t>&& data, WTF::CheckedUint32 usage);
    void bufferSubData(WTF::CheckedUint32 target, WTF::CheckedUint64 offset, std::span<const uint8_t>&& data);
    void readPixelsBufferObject(WebCore::IntRect&& arg0, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset, WTF::CheckedInt32 alignment, WTF::CheckedInt32 rowLength);
    void texImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels);
    void texImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset);
    void texSubImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels);
    void texSubImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset);
    void compressedTexImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, std::span<const uint8_t>&& data);
    void compressedTexImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset);
    void compressedTexSubImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, std::span<const uint8_t>&& data);
    void compressedTexSubImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset);
    void drawArraysInstanced(WTF::CheckedUint32 mode, WTF::CheckedInt32 first, WTF::CheckedInt32 count, WTF::CheckedInt32 primcount);
    void drawElementsInstanced(WTF::CheckedUint32 mode, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset, WTF::CheckedInt32 primcount);
    void vertexAttribDivisor(WTF::CheckedUint32 index, WTF::CheckedUint32 divisor);
    void createVertexArray(WTF::CheckedUint32 name);
    void deleteVertexArray(WTF::CheckedUint32 arg0);
    void isVertexArray(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&&);
    void bindVertexArray(WTF::CheckedUint32 arg0);
    void copyBufferSubData(WTF::CheckedUint32 readTarget, WTF::CheckedUint32 writeTarget, WTF::CheckedUint64 readOffset, WTF::CheckedUint64 writeOffset, WTF::CheckedUint64 arg4);
    void blitFramebuffer(WTF::CheckedInt32 srcX0, WTF::CheckedInt32 srcY0, WTF::CheckedInt32 srcX1, WTF::CheckedInt32 srcY1, WTF::CheckedInt32 dstX0, WTF::CheckedInt32 dstY0, WTF::CheckedInt32 dstX1, WTF::CheckedInt32 dstY1, WTF::CheckedUint32 mask, WTF::CheckedUint32 filter);
    void framebufferTextureLayer(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 texture, WTF::CheckedInt32 level, WTF::CheckedInt32 layer);
    void readBuffer(WTF::CheckedUint32 src);
    void renderbufferStorageMultisample(WTF::CheckedUint32 target, WTF::CheckedInt32 samples, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void texStorage2D(WTF::CheckedUint32 target, WTF::CheckedInt32 levels, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void texStorage3D(WTF::CheckedUint32 target, WTF::CheckedInt32 levels, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth);
    void texImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels);
    void texImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset);
    void texSubImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels);
    void texSubImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset);
    void copyTexSubImage3D(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void compressedTexImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, std::span<const uint8_t>&& data);
    void compressedTexImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset);
    void compressedTexSubImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, std::span<const uint8_t>&& data);
    void compressedTexSubImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset);
    void getFragDataLocation(WTF::CheckedUint32 program, CString&& name, CompletionHandler<void(int32_t)>&&);
    void uniform1ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0);
    void uniform2ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0, WTF::CheckedUint32 v1);
    void uniform3ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0, WTF::CheckedUint32 v1, WTF::CheckedUint32 v2);
    void uniform4ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0, WTF::CheckedUint32 v1, WTF::CheckedUint32 v2, WTF::CheckedUint32 v3);
    void uniform1uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data);
    void uniform2uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data);
    void uniform3uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data);
    void uniform4uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data);
    void uniformMatrix2x3fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix3x2fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix2x4fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix4x2fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix3x4fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix4x3fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data);
    void vertexAttribI4i(WTF::CheckedUint32 index, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 z, WTF::CheckedInt32 w);
    void vertexAttribI4iv(WTF::CheckedUint32 index, std::span<const int32_t, 4>&& values);
    void vertexAttribI4ui(WTF::CheckedUint32 index, WTF::CheckedUint32 x, WTF::CheckedUint32 y, WTF::CheckedUint32 z, WTF::CheckedUint32 w);
    void vertexAttribI4uiv(WTF::CheckedUint32 index, std::span<const uint32_t, 4>&& values);
    void vertexAttribIPointer(WTF::CheckedUint32 index, WTF::CheckedInt32 size, WTF::CheckedUint32 type, WTF::CheckedInt32 stride, WTF::CheckedUint64 offset);
    void drawRangeElements(WTF::CheckedUint32 mode, WTF::CheckedUint32 start, WTF::CheckedUint32 end, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset);
    void clearBufferiv(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, std::span<const int32_t>&& values);
    void clearBufferuiv(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, std::span<const uint32_t>&& values);
    void clearBufferfv(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, std::span<const float>&& values);
    void clearBufferfi(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, float depth, WTF::CheckedInt32 stencil);
    void createQuery(WTF::CheckedUint32 name);
    void deleteQuery(WTF::CheckedUint32 query);
    void isQuery(WTF::CheckedUint32 query, CompletionHandler<void(bool)>&&);
    void beginQuery(WTF::CheckedUint32 target, WTF::CheckedUint32 query);
    void endQuery(WTF::CheckedUint32 target);
    void getQuery(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getQueryObjectui(WTF::CheckedUint32 query, WTF::CheckedUint32 pname, CompletionHandler<void(uint32_t)>&&);
    void createSampler(WTF::CheckedUint32 name);
    void deleteSampler(WTF::CheckedUint32 sampler);
    void isSampler(WTF::CheckedUint32 sampler, CompletionHandler<void(bool)>&&);
    void bindSampler(WTF::CheckedUint32 unit, WTF::CheckedUint32 sampler);
    void samplerParameteri(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, WTF::CheckedInt32 param);
    void samplerParameterf(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, float param);
    void getSamplerParameterf(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, CompletionHandler<void(float)>&&);
    void getSamplerParameteri(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void fenceSync(WTF::CheckedUint32 condition, WTF::CheckedUint32 flags, CompletionHandler<void(uint64_t)>&&);
    void isSync(WTF::CheckedUint64 arg0, CompletionHandler<void(bool)>&&);
    void deleteSync(WTF::CheckedUint64 arg0);
    void clientWaitSync(WTF::CheckedUint64 arg0, WTF::CheckedUint32 flags, WTF::CheckedUint64 timeout, CompletionHandler<void(uint32_t)>&&);
    void waitSync(WTF::CheckedUint64 arg0, WTF::CheckedUint32 flags, WTF::CheckedInt64 timeout);
    void getSynci(WTF::CheckedUint64 arg0, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void createTransformFeedback(WTF::CheckedUint32 name);
    void deleteTransformFeedback(WTF::CheckedUint32 id);
    void isTransformFeedback(WTF::CheckedUint32 id, CompletionHandler<void(bool)>&&);
    void bindTransformFeedback(WTF::CheckedUint32 target, WTF::CheckedUint32 id);
    void beginTransformFeedback(WTF::CheckedUint32 primitiveMode);
    void endTransformFeedback();
    void transformFeedbackVaryings(WTF::CheckedUint32 program, Vector<CString>&& varyings, WTF::CheckedUint32 bufferMode);
    void getTransformFeedbackVarying(WTF::CheckedUint32 program, WTF::CheckedUint32 index, CompletionHandler<void(std::optional<WebCore::GCGLTransformFeedbackActiveInfo>&&)>&&);
    void pauseTransformFeedback();
    void resumeTransformFeedback();
    void bindBufferBase(WTF::CheckedUint32 target, WTF::CheckedUint32 index, WTF::CheckedUint32 buffer);
    void bindBufferRange(WTF::CheckedUint32 target, WTF::CheckedUint32 index, WTF::CheckedUint32 buffer, WTF::CheckedUint64 offset, WTF::CheckedUint64 arg4);
    void getUniformBlockIndex(WTF::CheckedUint32 program, CString&& uniformBlockName, CompletionHandler<void(uint32_t)>&&);
    void getActiveUniformBlockName(WTF::CheckedUint32 program, WTF::CheckedUint32 uniformBlockIndex, CompletionHandler<void(CString&&)>&&);
    void uniformBlockBinding(WTF::CheckedUint32 program, WTF::CheckedUint32 uniformBlockIndex, WTF::CheckedUint32 uniformBlockBinding);
    void getActiveUniformBlockiv(WTF::CheckedUint32 program, WTF::CheckedUint32 uniformBlockIndex, WTF::CheckedUint32 pname, WTF::CheckedUint64 paramsSize, CompletionHandler<void(std::span<const int32_t>)>&&);
    void getTranslatedShaderSourceANGLE(WTF::CheckedUint32 arg0, CompletionHandler<void(CString&&)>&&);
    void createQueryEXT(WTF::CheckedUint32 name);
    void deleteQueryEXT(WTF::CheckedUint32 query);
    void isQueryEXT(WTF::CheckedUint32 query, CompletionHandler<void(bool)>&&);
    void beginQueryEXT(WTF::CheckedUint32 target, WTF::CheckedUint32 query);
    void endQueryEXT(WTF::CheckedUint32 target);
    void queryCounterEXT(WTF::CheckedUint32 query, WTF::CheckedUint32 target);
    void getQueryiEXT(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getQueryObjectiEXT(WTF::CheckedUint32 query, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getQueryObjectui64EXT(WTF::CheckedUint32 query, WTF::CheckedUint32 pname, CompletionHandler<void(uint64_t)>&&);
    void getInteger64EXT(WTF::CheckedUint32 pname, CompletionHandler<void(int64_t)>&&);
    void enableiOES(WTF::CheckedUint32 target, WTF::CheckedUint32 index);
    void disableiOES(WTF::CheckedUint32 target, WTF::CheckedUint32 index);
    void blendEquationiOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 mode);
    void blendEquationSeparateiOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 modeRGB, WTF::CheckedUint32 modeAlpha);
    void blendFunciOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 src, WTF::CheckedUint32 dst);
    void blendFuncSeparateiOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 srcRGB, WTF::CheckedUint32 dstRGB, WTF::CheckedUint32 srcAlpha, WTF::CheckedUint32 dstAlpha);
    void colorMaskiOES(WTF::CheckedUint32 buf, bool red, bool green, bool blue, bool alpha);
    void drawArraysInstancedBaseInstanceANGLE(WTF::CheckedUint32 mode, WTF::CheckedInt32 first, WTF::CheckedInt32 count, WTF::CheckedInt32 instanceCount, WTF::CheckedUint32 baseInstance);
    void drawElementsInstancedBaseVertexBaseInstanceANGLE(WTF::CheckedUint32 mode, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset, WTF::CheckedInt32 instanceCount, WTF::CheckedInt32 baseVertex, WTF::CheckedUint32 baseInstance);
    void clipControlEXT(WTF::CheckedUint32 origin, WTF::CheckedUint32 depth);
    void provokingVertexANGLE(WTF::CheckedUint32 provokeMode);
    void polygonModeANGLE(WTF::CheckedUint32 face, WTF::CheckedUint32 mode);
    void polygonOffsetClampEXT(float factor, float units, float clamp);
    void renderbufferStorageMultisampleANGLE(WTF::CheckedUint32 target, WTF::CheckedInt32 samples, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height);
    void getInternalformativ(WTF::CheckedUint32 target, WTF::CheckedUint32 internalformat, WTF::CheckedUint32 pname, WTF::CheckedUint64 paramsSize, CompletionHandler<void(std::span<const int32_t>)>&&);
#if ENABLE(WEBXR)
    void createExternalImage(WTF::CheckedUint32 name, WebCore::GraphicsContextGL::ExternalImageSource&& arg0, WTF::CheckedUint32 internalFormat, WTF::CheckedInt32 layer);
    void deleteExternalImage(WTF::CheckedUint32 handle);
    void bindExternalImage(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1);
    void createExternalSync(WTF::CheckedUint32 name, WebCore::GraphicsContextGL::ExternalSyncSource&& arg0);
    void deleteExternalSync(WTF::CheckedUint32 arg0);
    void enableRequiredWebXRExtensions(CompletionHandler<void(bool)>&&);
    void addFoveation(WebCore::IntSize&& physicalSizeLeft, WebCore::IntSize&& physicalSizeRight, WebCore::IntSize&& screenSize, std::span<const float>&& horizontalSamplesLeft, std::span<const float>&& verticalSamples, std::span<const float>&& horizontalSamplesRight, CompletionHandler<void(bool)>&&);
    void enableFoveation(WTF::CheckedUint32 arg0);
    void disableFoveation();
    void framebufferResolveRenderbuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 renderbuffertarget, WTF::CheckedUint32 arg3);
#endif

