/* Copyright (C) 2020 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1.  Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 * 2.  Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// This file is generated by generate-gpup-webgl. Do not edit.
// This file should be included in the private section of the
// RemoteGraphicsContextGL implementations.
#pragma once
    void activeTexture(WTF::UntrustedUint32 texture);
    void attachShader(WTF::UntrustedUint32 program, WTF::UntrustedUint32 shader);
    void bindAttribLocation(WTF::UntrustedUint32 arg0, WTF::UntrustedUint32 index, CString&& name);
    void bindBuffer(WTF::UntrustedUint32 target, WTF::UntrustedUint32 arg1);
    void bindFramebuffer(WTF::UntrustedUint32 target, WTF::UntrustedUint32 arg1);
    void bindRenderbuffer(WTF::UntrustedUint32 target, WTF::UntrustedUint32 arg1);
    void bindTexture(WTF::UntrustedUint32 target, WTF::UntrustedUint32 arg1);
    void blendColor(float red, float green, float blue, float alpha);
    void blendEquation(WTF::UntrustedUint32 mode);
    void blendEquationSeparate(WTF::UntrustedUint32 modeRGB, WTF::UntrustedUint32 modeAlpha);
    void blendFunc(WTF::UntrustedUint32 sfactor, WTF::UntrustedUint32 dfactor);
    void blendFuncSeparate(WTF::UntrustedUint32 srcRGB, WTF::UntrustedUint32 dstRGB, WTF::UntrustedUint32 srcAlpha, WTF::UntrustedUint32 dstAlpha);
    void checkFramebufferStatus(WTF::UntrustedUint32 target, CompletionHandler<void(uint32_t)>&&);
    void clear(WTF::UntrustedUint32 mask);
    void clearColor(float red, float green, float blue, float alpha);
    void clearDepth(float depth);
    void clearStencil(WTF::UntrustedInt32 s);
    void colorMask(bool red, bool green, bool blue, bool alpha);
    void compileShader(WTF::UntrustedUint32 arg0);
    void copyTexImage2D(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 border);
    void copyTexSubImage2D(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void createBuffer(WTF::UntrustedUint32 name);
    void createFramebuffer(WTF::UntrustedUint32 name);
    void createProgram(WTF::UntrustedUint32 name);
    void createRenderbuffer(WTF::UntrustedUint32 name);
    void createShader(WTF::UntrustedUint32 name, WTF::UntrustedUint32 arg0);
    void createTexture(WTF::UntrustedUint32 name);
    void cullFace(WTF::UntrustedUint32 mode);
    void deleteBuffer(WTF::UntrustedUint32 arg0);
    void deleteFramebuffer(WTF::UntrustedUint32 arg0);
    void deleteProgram(WTF::UntrustedUint32 arg0);
    void deleteRenderbuffer(WTF::UntrustedUint32 arg0);
    void deleteShader(WTF::UntrustedUint32 arg0);
    void deleteTexture(WTF::UntrustedUint32 arg0);
    void depthFunc(WTF::UntrustedUint32 func);
    void depthMask(bool flag);
    void depthRange(float zNear, float zFar);
    void detachShader(WTF::UntrustedUint32 arg0, WTF::UntrustedUint32 arg1);
    void disable(WTF::UntrustedUint32 cap);
    void disableVertexAttribArray(WTF::UntrustedUint32 index);
    void drawArrays(WTF::UntrustedUint32 mode, WTF::UntrustedInt32 first, WTF::UntrustedInt32 count);
    void drawElements(WTF::UntrustedUint32 mode, WTF::UntrustedInt32 count, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset);
    void enable(WTF::UntrustedUint32 cap);
    void enableVertexAttribArray(WTF::UntrustedUint32 index);
    void finish();
    void flush();
    void framebufferRenderbuffer(WTF::UntrustedUint32 target, WTF::UntrustedUint32 attachment, WTF::UntrustedUint32 renderbuffertarget, WTF::UntrustedUint32 arg3);
    void framebufferTexture2D(WTF::UntrustedUint32 target, WTF::UntrustedUint32 attachment, WTF::UntrustedUint32 textarget, WTF::UntrustedUint32 arg3, WTF::UntrustedInt32 level);
    void frontFace(WTF::UntrustedUint32 mode);
    void generateMipmap(WTF::UntrustedUint32 target);
    void activeAttribs(WTF::UntrustedUint32 program, CompletionHandler<void(Vector<WebCore::GCGLAttribActiveInfo>&&)>&&);
    void activeUniforms(WTF::UntrustedUint32 program, CompletionHandler<void(Vector<WebCore::GCGLUniformActiveInfo>&&)>&&);
    void getBufferParameteri(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getString(WTF::UntrustedUint32 name, CompletionHandler<void(CString&&)>&&);
    void getFloatv(WTF::UntrustedUint32 pname, WTF::UntrustedUint64 valueSize, CompletionHandler<void(std::span<const float>)>&&);
    void getIntegerv(WTF::UntrustedUint32 pname, WTF::UntrustedUint64 valueSize, CompletionHandler<void(std::span<const int32_t>)>&&);
    void getIntegeri_v(WTF::UntrustedUint32 pname, WTF::UntrustedUint32 index, CompletionHandler<void(std::span<const int32_t, 4>)>&&); // NOLINT
    void getInteger64(WTF::UntrustedUint32 pname, CompletionHandler<void(int64_t)>&&);
    void getInteger64i(WTF::UntrustedUint32 pname, WTF::UntrustedUint32 index, CompletionHandler<void(int64_t)>&&);
    void getProgrami(WTF::UntrustedUint32 program, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getBooleanv(WTF::UntrustedUint32 pname, WTF::UntrustedUint64 valueSize, CompletionHandler<void(std::span<const bool>)>&&);
    void getFramebufferAttachmentParameteri(WTF::UntrustedUint32 target, WTF::UntrustedUint32 attachment, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getProgramInfoLog(WTF::UntrustedUint32 arg0, CompletionHandler<void(CString&&)>&&);
    void getRenderbufferParameteri(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getShaderi(WTF::UntrustedUint32 arg0, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getShaderInfoLog(WTF::UntrustedUint32 arg0, CompletionHandler<void(CString&&)>&&);
    void getShaderPrecisionFormat(WTF::UntrustedUint32 shaderType, WTF::UntrustedUint32 precisionType, CompletionHandler<void(std::span<const int32_t, 2>, int32_t)>&&);
    void getTexParameterf(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, CompletionHandler<void(float)>&&);
    void getTexParameteri(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getUniformfv(WTF::UntrustedUint32 program, WTF::UntrustedInt32 location, WTF::UntrustedUint64 valueSize, CompletionHandler<void(std::span<const float>)>&&);
    void getUniformiv(WTF::UntrustedUint32 program, WTF::UntrustedInt32 location, WTF::UntrustedUint64 valueSize, CompletionHandler<void(std::span<const int32_t>)>&&);
    void getUniformuiv(WTF::UntrustedUint32 program, WTF::UntrustedInt32 location, WTF::UntrustedUint64 valueSize, CompletionHandler<void(std::span<const uint32_t>)>&&);
    void getVertexAttribOffset(WTF::UntrustedUint32 index, WTF::UntrustedUint32 pname, CompletionHandler<void(uint64_t)>&&);
    void hint(WTF::UntrustedUint32 target, WTF::UntrustedUint32 mode);
    void isBuffer(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isEnabled(WTF::UntrustedUint32 cap, CompletionHandler<void(bool)>&&);
    void isFramebuffer(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isProgram(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isRenderbuffer(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isShader(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void isTexture(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void lineWidth(float arg0);
    void linkProgram(WTF::UntrustedUint32 arg0);
    void pixelStorei(WTF::UntrustedUint32 pname, WTF::UntrustedInt32 param);
    void polygonOffset(float factor, float units);
    void renderbufferStorage(WTF::UntrustedUint32 target, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void sampleCoverage(float value, bool invert);
    void scissor(WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void shaderSource(WTF::UntrustedUint32 arg0, CString&& arg1);
    void stencilFunc(WTF::UntrustedUint32 func, WTF::UntrustedInt32 ref, WTF::UntrustedUint32 mask);
    void stencilFuncSeparate(WTF::UntrustedUint32 face, WTF::UntrustedUint32 func, WTF::UntrustedInt32 ref, WTF::UntrustedUint32 mask);
    void stencilMask(WTF::UntrustedUint32 mask);
    void stencilMaskSeparate(WTF::UntrustedUint32 face, WTF::UntrustedUint32 mask);
    void stencilOp(WTF::UntrustedUint32 fail, WTF::UntrustedUint32 zfail, WTF::UntrustedUint32 zpass);
    void stencilOpSeparate(WTF::UntrustedUint32 face, WTF::UntrustedUint32 fail, WTF::UntrustedUint32 zfail, WTF::UntrustedUint32 zpass);
    void texParameterf(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, float param);
    void texParameteri(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, WTF::UntrustedInt32 param);
    void uniform1f(WTF::UntrustedInt32 location, float x);
    void uniform1fv(WTF::UntrustedInt32 location, std::span<const float>&& v);
    void uniform1i(WTF::UntrustedInt32 location, WTF::UntrustedInt32 x);
    void uniform1iv(WTF::UntrustedInt32 location, std::span<const int32_t>&& v);
    void uniform2f(WTF::UntrustedInt32 location, float x, float y);
    void uniform2fv(WTF::UntrustedInt32 location, std::span<const float>&& v);
    void uniform2i(WTF::UntrustedInt32 location, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y);
    void uniform2iv(WTF::UntrustedInt32 location, std::span<const int32_t>&& v);
    void uniform3f(WTF::UntrustedInt32 location, float x, float y, float z);
    void uniform3fv(WTF::UntrustedInt32 location, std::span<const float>&& v);
    void uniform3i(WTF::UntrustedInt32 location, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 z);
    void uniform3iv(WTF::UntrustedInt32 location, std::span<const int32_t>&& v);
    void uniform4f(WTF::UntrustedInt32 location, float x, float y, float z, float w);
    void uniform4fv(WTF::UntrustedInt32 location, std::span<const float>&& v);
    void uniform4i(WTF::UntrustedInt32 location, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 z, WTF::UntrustedInt32 w);
    void uniform4iv(WTF::UntrustedInt32 location, std::span<const int32_t>&& v);
    void uniformMatrix2fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& value);
    void uniformMatrix3fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& value);
    void uniformMatrix4fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& value);
    void useProgram(WTF::UntrustedUint32 arg0);
    void validateProgram(WTF::UntrustedUint32 arg0);
    void vertexAttrib1f(WTF::UntrustedUint32 index, float x);
    void vertexAttrib1fv(WTF::UntrustedUint32 index, std::span<const float, 1>&& values);
    void vertexAttrib2f(WTF::UntrustedUint32 index, float x, float y);
    void vertexAttrib2fv(WTF::UntrustedUint32 index, std::span<const float, 2>&& values);
    void vertexAttrib3f(WTF::UntrustedUint32 index, float x, float y, float z);
    void vertexAttrib3fv(WTF::UntrustedUint32 index, std::span<const float, 3>&& values);
    void vertexAttrib4f(WTF::UntrustedUint32 index, float x, float y, float z, float w);
    void vertexAttrib4fv(WTF::UntrustedUint32 index, std::span<const float, 4>&& values);
    void vertexAttribPointer(WTF::UntrustedUint32 index, WTF::UntrustedInt32 size, WTF::UntrustedUint32 type, bool normalized, WTF::UntrustedInt32 stride, WTF::UntrustedUint64 offset);
    void viewport(WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void bufferData0(WTF::UntrustedUint32 target, WTF::UntrustedUint64 arg1, WTF::UntrustedUint32 usage);
    void bufferData1(WTF::UntrustedUint32 target, std::span<const uint8_t>&& data, WTF::UntrustedUint32 usage);
    void bufferSubData(WTF::UntrustedUint32 target, WTF::UntrustedUint64 offset, std::span<const uint8_t>&& data);
    void readPixelsBufferObject(WebCore::IntRect&& arg0, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset, WTF::UntrustedInt32 alignment, WTF::UntrustedInt32 rowLength);
    void texImage2D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 border, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, std::span<const uint8_t>&& pixels);
    void texImage2D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 border, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset);
    void texSubImage2D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, std::span<const uint8_t>&& pixels);
    void texSubImage2D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset);
    void compressedTexImage2D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 border, std::span<const uint8_t>&& data);
    void compressedTexImage2D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 border, WTF::UntrustedInt32 imageSize, WTF::UntrustedUint64 offset);
    void compressedTexSubImage2D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedUint32 format, std::span<const uint8_t>&& data);
    void compressedTexSubImage2D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedUint32 format, WTF::UntrustedInt32 imageSize, WTF::UntrustedUint64 offset);
    void drawArraysInstanced(WTF::UntrustedUint32 mode, WTF::UntrustedInt32 first, WTF::UntrustedInt32 count, WTF::UntrustedInt32 primcount);
    void drawElementsInstanced(WTF::UntrustedUint32 mode, WTF::UntrustedInt32 count, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset, WTF::UntrustedInt32 primcount);
    void vertexAttribDivisor(WTF::UntrustedUint32 index, WTF::UntrustedUint32 divisor);
    void createVertexArray(WTF::UntrustedUint32 name);
    void deleteVertexArray(WTF::UntrustedUint32 arg0);
    void isVertexArray(WTF::UntrustedUint32 arg0, CompletionHandler<void(bool)>&&);
    void bindVertexArray(WTF::UntrustedUint32 arg0);
    void copyBufferSubData(WTF::UntrustedUint32 readTarget, WTF::UntrustedUint32 writeTarget, WTF::UntrustedUint64 readOffset, WTF::UntrustedUint64 writeOffset, WTF::UntrustedUint64 arg4);
    void blitFramebuffer(WTF::UntrustedInt32 srcX0, WTF::UntrustedInt32 srcY0, WTF::UntrustedInt32 srcX1, WTF::UntrustedInt32 srcY1, WTF::UntrustedInt32 dstX0, WTF::UntrustedInt32 dstY0, WTF::UntrustedInt32 dstX1, WTF::UntrustedInt32 dstY1, WTF::UntrustedUint32 mask, WTF::UntrustedUint32 filter);
    void framebufferTextureLayer(WTF::UntrustedUint32 target, WTF::UntrustedUint32 attachment, WTF::UntrustedUint32 texture, WTF::UntrustedInt32 level, WTF::UntrustedInt32 layer);
    void readBuffer(WTF::UntrustedUint32 src);
    void renderbufferStorageMultisample(WTF::UntrustedUint32 target, WTF::UntrustedInt32 samples, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void texStorage2D(WTF::UntrustedUint32 target, WTF::UntrustedInt32 levels, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void texStorage3D(WTF::UntrustedUint32 target, WTF::UntrustedInt32 levels, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth);
    void texImage3D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedInt32 border, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, std::span<const uint8_t>&& pixels);
    void texImage3D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedInt32 border, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset);
    void texSubImage3D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 zoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, std::span<const uint8_t>&& pixels);
    void texSubImage3D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 zoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedUint32 format, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset);
    void copyTexSubImage3D(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 zoffset, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void compressedTexImage3D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedInt32 border, std::span<const uint8_t>&& data);
    void compressedTexImage3D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedInt32 border, WTF::UntrustedInt32 imageSize, WTF::UntrustedUint64 offset);
    void compressedTexSubImage3D0(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 zoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedUint32 format, std::span<const uint8_t>&& data);
    void compressedTexSubImage3D1(WTF::UntrustedUint32 target, WTF::UntrustedInt32 level, WTF::UntrustedInt32 xoffset, WTF::UntrustedInt32 yoffset, WTF::UntrustedInt32 zoffset, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height, WTF::UntrustedInt32 depth, WTF::UntrustedUint32 format, WTF::UntrustedInt32 imageSize, WTF::UntrustedUint64 offset);
    void getFragDataLocation(WTF::UntrustedUint32 program, CString&& name, CompletionHandler<void(int32_t)>&&);
    void uniform1ui(WTF::UntrustedInt32 location, WTF::UntrustedUint32 v0);
    void uniform2ui(WTF::UntrustedInt32 location, WTF::UntrustedUint32 v0, WTF::UntrustedUint32 v1);
    void uniform3ui(WTF::UntrustedInt32 location, WTF::UntrustedUint32 v0, WTF::UntrustedUint32 v1, WTF::UntrustedUint32 v2);
    void uniform4ui(WTF::UntrustedInt32 location, WTF::UntrustedUint32 v0, WTF::UntrustedUint32 v1, WTF::UntrustedUint32 v2, WTF::UntrustedUint32 v3);
    void uniform1uiv(WTF::UntrustedInt32 location, std::span<const uint32_t>&& data);
    void uniform2uiv(WTF::UntrustedInt32 location, std::span<const uint32_t>&& data);
    void uniform3uiv(WTF::UntrustedInt32 location, std::span<const uint32_t>&& data);
    void uniform4uiv(WTF::UntrustedInt32 location, std::span<const uint32_t>&& data);
    void uniformMatrix2x3fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix3x2fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix2x4fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix4x2fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix3x4fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& data);
    void uniformMatrix4x3fv(WTF::UntrustedInt32 location, bool transpose, std::span<const float>&& data);
    void vertexAttribI4i(WTF::UntrustedUint32 index, WTF::UntrustedInt32 x, WTF::UntrustedInt32 y, WTF::UntrustedInt32 z, WTF::UntrustedInt32 w);
    void vertexAttribI4iv(WTF::UntrustedUint32 index, std::span<const int32_t, 4>&& values);
    void vertexAttribI4ui(WTF::UntrustedUint32 index, WTF::UntrustedUint32 x, WTF::UntrustedUint32 y, WTF::UntrustedUint32 z, WTF::UntrustedUint32 w);
    void vertexAttribI4uiv(WTF::UntrustedUint32 index, std::span<const uint32_t, 4>&& values);
    void vertexAttribIPointer(WTF::UntrustedUint32 index, WTF::UntrustedInt32 size, WTF::UntrustedUint32 type, WTF::UntrustedInt32 stride, WTF::UntrustedUint64 offset);
    void drawRangeElements(WTF::UntrustedUint32 mode, WTF::UntrustedUint32 start, WTF::UntrustedUint32 end, WTF::UntrustedInt32 count, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset);
    void clearBufferiv(WTF::UntrustedUint32 buffer, WTF::UntrustedInt32 drawbuffer, std::span<const int32_t>&& values);
    void clearBufferuiv(WTF::UntrustedUint32 buffer, WTF::UntrustedInt32 drawbuffer, std::span<const uint32_t>&& values);
    void clearBufferfv(WTF::UntrustedUint32 buffer, WTF::UntrustedInt32 drawbuffer, std::span<const float>&& values);
    void clearBufferfi(WTF::UntrustedUint32 buffer, WTF::UntrustedInt32 drawbuffer, float depth, WTF::UntrustedInt32 stencil);
    void createQuery(WTF::UntrustedUint32 name);
    void deleteQuery(WTF::UntrustedUint32 query);
    void isQuery(WTF::UntrustedUint32 query, CompletionHandler<void(bool)>&&);
    void beginQuery(WTF::UntrustedUint32 target, WTF::UntrustedUint32 query);
    void endQuery(WTF::UntrustedUint32 target);
    void getQuery(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getQueryObjectui(WTF::UntrustedUint32 query, WTF::UntrustedUint32 pname, CompletionHandler<void(uint32_t)>&&);
    void createSampler(WTF::UntrustedUint32 name);
    void deleteSampler(WTF::UntrustedUint32 sampler);
    void isSampler(WTF::UntrustedUint32 sampler, CompletionHandler<void(bool)>&&);
    void bindSampler(WTF::UntrustedUint32 unit, WTF::UntrustedUint32 sampler);
    void samplerParameteri(WTF::UntrustedUint32 sampler, WTF::UntrustedUint32 pname, WTF::UntrustedInt32 param);
    void samplerParameterf(WTF::UntrustedUint32 sampler, WTF::UntrustedUint32 pname, float param);
    void getSamplerParameterf(WTF::UntrustedUint32 sampler, WTF::UntrustedUint32 pname, CompletionHandler<void(float)>&&);
    void getSamplerParameteri(WTF::UntrustedUint32 sampler, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void fenceSync(WTF::UntrustedUint32 condition, WTF::UntrustedUint32 flags, CompletionHandler<void(uint64_t)>&&);
    void isSync(WTF::UntrustedUint64 arg0, CompletionHandler<void(bool)>&&);
    void deleteSync(WTF::UntrustedUint64 arg0);
    void clientWaitSync(WTF::UntrustedUint64 arg0, WTF::UntrustedUint32 flags, WTF::UntrustedUint64 timeout, CompletionHandler<void(uint32_t)>&&);
    void waitSync(WTF::UntrustedUint64 arg0, WTF::UntrustedUint32 flags, WTF::UntrustedInt64 timeout);
    void getSynci(WTF::UntrustedUint64 arg0, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void createTransformFeedback(WTF::UntrustedUint32 name);
    void deleteTransformFeedback(WTF::UntrustedUint32 id);
    void isTransformFeedback(WTF::UntrustedUint32 id, CompletionHandler<void(bool)>&&);
    void bindTransformFeedback(WTF::UntrustedUint32 target, WTF::UntrustedUint32 id);
    void beginTransformFeedback(WTF::UntrustedUint32 primitiveMode);
    void endTransformFeedback();
    void transformFeedbackVaryings(WTF::UntrustedUint32 program, Vector<CString>&& varyings, WTF::UntrustedUint32 bufferMode);
    void getTransformFeedbackVarying(WTF::UntrustedUint32 program, WTF::UntrustedUint32 index, CompletionHandler<void(std::optional<WebCore::GCGLTransformFeedbackActiveInfo>&&)>&&);
    void pauseTransformFeedback();
    void resumeTransformFeedback();
    void bindBufferBase(WTF::UntrustedUint32 target, WTF::UntrustedUint32 index, WTF::UntrustedUint32 buffer);
    void bindBufferRange(WTF::UntrustedUint32 target, WTF::UntrustedUint32 index, WTF::UntrustedUint32 buffer, WTF::UntrustedUint64 offset, WTF::UntrustedUint64 arg4);
    void getUniformBlockIndex(WTF::UntrustedUint32 program, CString&& uniformBlockName, CompletionHandler<void(uint32_t)>&&);
    void getActiveUniformBlockName(WTF::UntrustedUint32 program, WTF::UntrustedUint32 uniformBlockIndex, CompletionHandler<void(CString&&)>&&);
    void uniformBlockBinding(WTF::UntrustedUint32 program, WTF::UntrustedUint32 uniformBlockIndex, WTF::UntrustedUint32 uniformBlockBinding);
    void getActiveUniformBlockiv(WTF::UntrustedUint32 program, WTF::UntrustedUint32 uniformBlockIndex, WTF::UntrustedUint32 pname, WTF::UntrustedUint64 paramsSize, CompletionHandler<void(std::span<const int32_t>)>&&);
    void getTranslatedShaderSourceANGLE(WTF::UntrustedUint32 arg0, CompletionHandler<void(CString&&)>&&);
    void createQueryEXT(WTF::UntrustedUint32 name);
    void deleteQueryEXT(WTF::UntrustedUint32 query);
    void isQueryEXT(WTF::UntrustedUint32 query, CompletionHandler<void(bool)>&&);
    void beginQueryEXT(WTF::UntrustedUint32 target, WTF::UntrustedUint32 query);
    void endQueryEXT(WTF::UntrustedUint32 target);
    void queryCounterEXT(WTF::UntrustedUint32 query, WTF::UntrustedUint32 target);
    void getQueryiEXT(WTF::UntrustedUint32 target, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getQueryObjectiEXT(WTF::UntrustedUint32 query, WTF::UntrustedUint32 pname, CompletionHandler<void(int32_t)>&&);
    void getQueryObjectui64EXT(WTF::UntrustedUint32 query, WTF::UntrustedUint32 pname, CompletionHandler<void(uint64_t)>&&);
    void getInteger64EXT(WTF::UntrustedUint32 pname, CompletionHandler<void(int64_t)>&&);
    void enableiOES(WTF::UntrustedUint32 target, WTF::UntrustedUint32 index);
    void disableiOES(WTF::UntrustedUint32 target, WTF::UntrustedUint32 index);
    void blendEquationiOES(WTF::UntrustedUint32 buf, WTF::UntrustedUint32 mode);
    void blendEquationSeparateiOES(WTF::UntrustedUint32 buf, WTF::UntrustedUint32 modeRGB, WTF::UntrustedUint32 modeAlpha);
    void blendFunciOES(WTF::UntrustedUint32 buf, WTF::UntrustedUint32 src, WTF::UntrustedUint32 dst);
    void blendFuncSeparateiOES(WTF::UntrustedUint32 buf, WTF::UntrustedUint32 srcRGB, WTF::UntrustedUint32 dstRGB, WTF::UntrustedUint32 srcAlpha, WTF::UntrustedUint32 dstAlpha);
    void colorMaskiOES(WTF::UntrustedUint32 buf, bool red, bool green, bool blue, bool alpha);
    void drawArraysInstancedBaseInstanceANGLE(WTF::UntrustedUint32 mode, WTF::UntrustedInt32 first, WTF::UntrustedInt32 count, WTF::UntrustedInt32 instanceCount, WTF::UntrustedUint32 baseInstance);
    void drawElementsInstancedBaseVertexBaseInstanceANGLE(WTF::UntrustedUint32 mode, WTF::UntrustedInt32 count, WTF::UntrustedUint32 type, WTF::UntrustedUint64 offset, WTF::UntrustedInt32 instanceCount, WTF::UntrustedInt32 baseVertex, WTF::UntrustedUint32 baseInstance);
    void clipControlEXT(WTF::UntrustedUint32 origin, WTF::UntrustedUint32 depth);
    void provokingVertexANGLE(WTF::UntrustedUint32 provokeMode);
    void polygonModeANGLE(WTF::UntrustedUint32 face, WTF::UntrustedUint32 mode);
    void polygonOffsetClampEXT(float factor, float units, float clamp);
    void renderbufferStorageMultisampleANGLE(WTF::UntrustedUint32 target, WTF::UntrustedInt32 samples, WTF::UntrustedUint32 internalformat, WTF::UntrustedInt32 width, WTF::UntrustedInt32 height);
    void getInternalformativ(WTF::UntrustedUint32 target, WTF::UntrustedUint32 internalformat, WTF::UntrustedUint32 pname, WTF::UntrustedUint64 paramsSize, CompletionHandler<void(std::span<const int32_t>)>&&);
#if ENABLE(WEBXR)
    void createExternalImage(WTF::UntrustedUint32 name, WebCore::GraphicsContextGL::ExternalImageSource&& arg0, WTF::UntrustedUint32 internalFormat, WTF::UntrustedInt32 layer);
    void deleteExternalImage(WTF::UntrustedUint32 handle);
    void bindExternalImage(WTF::UntrustedUint32 target, WTF::UntrustedUint32 arg1);
    void createExternalSync(WTF::UntrustedUint32 name, WebCore::GraphicsContextGL::ExternalSyncSource&& arg0);
    void deleteExternalSync(WTF::UntrustedUint32 arg0);
    void enableRequiredWebXRExtensions(CompletionHandler<void(bool)>&&);
    void addFoveation(WebCore::IntSize&& physicalSizeLeft, WebCore::IntSize&& physicalSizeRight, WebCore::IntSize&& screenSize, std::span<const float>&& horizontalSamplesLeft, std::span<const float>&& verticalSamples, std::span<const float>&& horizontalSamplesRight, CompletionHandler<void(bool)>&&);
    void enableFoveation(WTF::UntrustedUint32 arg0);
    void disableFoveation();
    void framebufferResolveRenderbuffer(WTF::UntrustedUint32 target, WTF::UntrustedUint32 attachment, WTF::UntrustedUint32 renderbuffertarget, WTF::UntrustedUint32 arg3);
#endif

