/* Copyright (C) 2020 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1.  Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 * 2.  Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// This file is generated by generate-gpup-webgl. Do not edit.

#include "config.h"
#include "RemoteGraphicsContextGL.h"

#include "Logging.h"
#include <wtf/StdLibExtras.h>

#if ENABLE(GPU_PROCESS) && ENABLE(WEBGL)

#define MESSAGE_CHECK(assertion) MESSAGE_CHECK_BASE(assertion, m_connection);

namespace WebKit {
using namespace WebCore;

void RemoteGraphicsContextGL::activeTexture(WTF::CheckedUint32 texture)
{
    assertIsCurrent(workQueue());
    protect(m_context)->activeTexture(texture);
}

void RemoteGraphicsContextGL::attachShader(WTF::CheckedUint32 program, WTF::CheckedUint32 shader)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    MESSAGE_CHECK(m_objectNames.isValidKey(shader));
    if (shader)
        shader = m_objectNames.get(shader);
    protect(m_context)->attachShader(program, shader);
}

void RemoteGraphicsContextGL::bindAttribLocation(WTF::CheckedUint32 arg0, WTF::CheckedUint32 index, CString&& name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->bindAttribLocation(arg0, index, name);
}

void RemoteGraphicsContextGL::bindBuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg1));
    if (arg1)
        arg1 = m_objectNames.get(arg1);
    protect(m_context)->bindBuffer(target, arg1);
}

void RemoteGraphicsContextGL::bindFramebuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg1));
    if (arg1)
        arg1 = m_objectNames.get(arg1);
    protect(m_context)->bindFramebuffer(target, arg1);
}

void RemoteGraphicsContextGL::bindRenderbuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg1));
    if (arg1)
        arg1 = m_objectNames.get(arg1);
    protect(m_context)->bindRenderbuffer(target, arg1);
}

void RemoteGraphicsContextGL::bindTexture(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg1));
    if (arg1)
        arg1 = m_objectNames.get(arg1);
    protect(m_context)->bindTexture(target, arg1);
}

void RemoteGraphicsContextGL::blendColor(float red, float green, float blue, float alpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendColor(red, green, blue, alpha);
}

void RemoteGraphicsContextGL::blendEquation(WTF::CheckedUint32 mode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendEquation(mode);
}

void RemoteGraphicsContextGL::blendEquationSeparate(WTF::CheckedUint32 modeRGB, WTF::CheckedUint32 modeAlpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendEquationSeparate(modeRGB, modeAlpha);
}

void RemoteGraphicsContextGL::blendFunc(WTF::CheckedUint32 sfactor, WTF::CheckedUint32 dfactor)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendFunc(sfactor, dfactor);
}

void RemoteGraphicsContextGL::blendFuncSeparate(WTF::CheckedUint32 srcRGB, WTF::CheckedUint32 dstRGB, WTF::CheckedUint32 srcAlpha, WTF::CheckedUint32 dstAlpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha);
}

void RemoteGraphicsContextGL::checkFramebufferStatus(WTF::CheckedUint32 target, CompletionHandler<void(uint32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLenum returnValue = { };
    returnValue = protect(m_context)->checkFramebufferStatus(target);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::clear(WTF::CheckedUint32 mask)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clear(mask);
}

void RemoteGraphicsContextGL::clearColor(float red, float green, float blue, float alpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearColor(red, green, blue, alpha);
}

void RemoteGraphicsContextGL::clearDepth(float depth)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearDepth(depth);
}

void RemoteGraphicsContextGL::clearStencil(WTF::CheckedInt32 s)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearStencil(s);
}

void RemoteGraphicsContextGL::colorMask(bool red, bool green, bool blue, bool alpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->colorMask(static_cast<GCGLboolean>(red), static_cast<GCGLboolean>(green), static_cast<GCGLboolean>(blue), static_cast<GCGLboolean>(alpha));
}

void RemoteGraphicsContextGL::compileShader(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->compileShader(arg0);
}

void RemoteGraphicsContextGL::copyTexImage2D(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border)
{
    assertIsCurrent(workQueue());
    protect(m_context)->copyTexImage2D(target, level, internalformat, x, y, width, height, border);
}

void RemoteGraphicsContextGL::copyTexSubImage2D(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->copyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
}

void RemoteGraphicsContextGL::createBuffer(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createBuffer();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::createFramebuffer(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createFramebuffer();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::createProgram(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createProgram();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::createRenderbuffer(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createRenderbuffer();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::createShader(WTF::CheckedUint32 name, WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createShader(arg0);
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::createTexture(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createTexture();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::cullFace(WTF::CheckedUint32 mode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->cullFace(mode);
}

void RemoteGraphicsContextGL::deleteBuffer(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteBuffer(arg0);
}

void RemoteGraphicsContextGL::deleteFramebuffer(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteFramebuffer(arg0);
}

void RemoteGraphicsContextGL::deleteProgram(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteProgram(arg0);
}

void RemoteGraphicsContextGL::deleteRenderbuffer(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteRenderbuffer(arg0);
}

void RemoteGraphicsContextGL::deleteShader(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteShader(arg0);
}

void RemoteGraphicsContextGL::deleteTexture(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteTexture(arg0);
}

void RemoteGraphicsContextGL::depthFunc(WTF::CheckedUint32 func)
{
    assertIsCurrent(workQueue());
    protect(m_context)->depthFunc(func);
}

void RemoteGraphicsContextGL::depthMask(bool flag)
{
    assertIsCurrent(workQueue());
    protect(m_context)->depthMask(static_cast<GCGLboolean>(flag));
}

void RemoteGraphicsContextGL::depthRange(float zNear, float zFar)
{
    assertIsCurrent(workQueue());
    protect(m_context)->depthRange(zNear, zFar);
}

void RemoteGraphicsContextGL::detachShader(WTF::CheckedUint32 arg0, WTF::CheckedUint32 arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    MESSAGE_CHECK(m_objectNames.isValidKey(arg1));
    if (arg1)
        arg1 = m_objectNames.get(arg1);
    protect(m_context)->detachShader(arg0, arg1);
}

void RemoteGraphicsContextGL::disable(WTF::CheckedUint32 cap)
{
    assertIsCurrent(workQueue());
    protect(m_context)->disable(cap);
}

void RemoteGraphicsContextGL::disableVertexAttribArray(WTF::CheckedUint32 index)
{
    assertIsCurrent(workQueue());
    protect(m_context)->disableVertexAttribArray(index);
}

void RemoteGraphicsContextGL::drawArrays(WTF::CheckedUint32 mode, WTF::CheckedInt32 first, WTF::CheckedInt32 count)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawArrays(mode, first, count);
}

void RemoteGraphicsContextGL::drawElements(WTF::CheckedUint32 mode, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawElements(mode, count, type, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::enable(WTF::CheckedUint32 cap)
{
    assertIsCurrent(workQueue());
    protect(m_context)->enable(cap);
}

void RemoteGraphicsContextGL::enableVertexAttribArray(WTF::CheckedUint32 index)
{
    assertIsCurrent(workQueue());
    protect(m_context)->enableVertexAttribArray(index);
}

void RemoteGraphicsContextGL::finish()
{
    assertIsCurrent(workQueue());
    protect(m_context)->finish();
}

void RemoteGraphicsContextGL::flush()
{
    assertIsCurrent(workQueue());
    protect(m_context)->flush();
}

void RemoteGraphicsContextGL::framebufferRenderbuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 renderbuffertarget, WTF::CheckedUint32 arg3)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg3));
    if (arg3)
        arg3 = m_objectNames.get(arg3);
    protect(m_context)->framebufferRenderbuffer(target, attachment, renderbuffertarget, arg3);
}

void RemoteGraphicsContextGL::framebufferTexture2D(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 textarget, WTF::CheckedUint32 arg3, WTF::CheckedInt32 level)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg3));
    if (arg3)
        arg3 = m_objectNames.get(arg3);
    protect(m_context)->framebufferTexture2D(target, attachment, textarget, arg3, level);
}

void RemoteGraphicsContextGL::frontFace(WTF::CheckedUint32 mode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->frontFace(mode);
}

void RemoteGraphicsContextGL::generateMipmap(WTF::CheckedUint32 target)
{
    assertIsCurrent(workQueue());
    protect(m_context)->generateMipmap(target);
}

void RemoteGraphicsContextGL::activeAttribs(WTF::CheckedUint32 program, CompletionHandler<void(Vector<WebCore::GCGLAttribActiveInfo>&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    Vector<WebCore::GCGLAttribActiveInfo> returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->activeAttribs(program);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::activeUniforms(WTF::CheckedUint32 program, CompletionHandler<void(Vector<WebCore::GCGLUniformActiveInfo>&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    Vector<WebCore::GCGLUniformActiveInfo> returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->activeUniforms(program);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::getBufferParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getBufferParameteri(target, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getString(WTF::CheckedUint32 name, CompletionHandler<void(CString&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    CString returnValue = { };
    returnValue = protect(m_context)->getString(name);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::getFloatv(WTF::CheckedUint32 pname, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const float>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    if (!WTF::isValidCapacityForVector<GCGLfloat>(valueSize))
        valueSize = 16;
    Vector<GCGLfloat, 16> value(FillWith { }, valueSize, 0);
    protect(m_context)->getFloatv(pname, value);
    completionHandler(spanReinterpretCast<const float>(value.span()));
}

void RemoteGraphicsContextGL::getIntegerv(WTF::CheckedUint32 pname, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const int32_t>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    if (!WTF::isValidCapacityForVector<GCGLint>(valueSize))
        valueSize = 4;
    Vector<GCGLint, 4> value(FillWith { }, valueSize, 0);
    protect(m_context)->getIntegerv(pname, value);
    completionHandler(spanReinterpretCast<const int32_t>(value.span()));
}

void RemoteGraphicsContextGL::getIntegeri_v(WTF::CheckedUint32 pname, WTF::CheckedUint32 index, CompletionHandler<void(std::span<const int32_t, 4>)>&& completionHandler) // NOLINT
{
    assertIsCurrent(workQueue());
    std::array<GCGLint, 4> value { };
    protect(m_context)->getIntegeri_v(pname, index, value);
    completionHandler(spanReinterpretCast<const int32_t, 4>(std::span<const GCGLint, 4>(value)));
}

void RemoteGraphicsContextGL::getInteger64(WTF::CheckedUint32 pname, CompletionHandler<void(int64_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint64 returnValue = { };
    returnValue = protect(m_context)->getInteger64(pname);
    completionHandler(static_cast<int64_t>(returnValue));
}

void RemoteGraphicsContextGL::getInteger64i(WTF::CheckedUint32 pname, WTF::CheckedUint32 index, CompletionHandler<void(int64_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint64 returnValue = { };
    returnValue = protect(m_context)->getInteger64i(pname, index);
    completionHandler(static_cast<int64_t>(returnValue));
}

void RemoteGraphicsContextGL::getProgrami(WTF::CheckedUint32 program, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->getProgrami(program, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getBooleanv(WTF::CheckedUint32 pname, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const bool>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    if (!WTF::isValidCapacityForVector<GCGLboolean>(valueSize))
        valueSize = 4;
    Vector<GCGLboolean, 4> value(FillWith { }, valueSize, 0);
    protect(m_context)->getBooleanv(pname, value);
    completionHandler(spanReinterpretCast<const bool>(value.span()));
}

void RemoteGraphicsContextGL::getFramebufferAttachmentParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getFramebufferAttachmentParameteri(target, attachment, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getProgramInfoLog(WTF::CheckedUint32 arg0, CompletionHandler<void(CString&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    CString returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->getProgramInfoLog(arg0);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::getRenderbufferParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getRenderbufferParameteri(target, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getShaderi(WTF::CheckedUint32 arg0, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->getShaderi(arg0, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getShaderInfoLog(WTF::CheckedUint32 arg0, CompletionHandler<void(CString&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    CString returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->getShaderInfoLog(arg0);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::getShaderPrecisionFormat(WTF::CheckedUint32 shaderType, WTF::CheckedUint32 precisionType, CompletionHandler<void(std::span<const int32_t, 2>, int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    std::array<GCGLint, 2> range { };
    GCGLint precision = { };
    protect(m_context)->getShaderPrecisionFormat(shaderType, precisionType, range, &precision);
    completionHandler(spanReinterpretCast<const int32_t, 2>(std::span<const GCGLint, 2>(range)), precision);
}

void RemoteGraphicsContextGL::getTexParameterf(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(float)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLfloat returnValue = { };
    returnValue = protect(m_context)->getTexParameterf(target, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getTexParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getTexParameteri(target, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getUniformfv(WTF::CheckedUint32 program, WTF::CheckedInt32 location, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const float>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    if (!WTF::isValidCapacityForVector<GCGLfloat>(valueSize))
        valueSize = 16;
    Vector<GCGLfloat, 16> value(FillWith { }, valueSize, 0);
    protect(m_context)->getUniformfv(program, location, value);
    completionHandler(spanReinterpretCast<const float>(value.span()));
}

void RemoteGraphicsContextGL::getUniformiv(WTF::CheckedUint32 program, WTF::CheckedInt32 location, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const int32_t>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    if (!WTF::isValidCapacityForVector<GCGLint>(valueSize))
        valueSize = 4;
    Vector<GCGLint, 4> value(FillWith { }, valueSize, 0);
    protect(m_context)->getUniformiv(program, location, value);
    completionHandler(spanReinterpretCast<const int32_t>(value.span()));
}

void RemoteGraphicsContextGL::getUniformuiv(WTF::CheckedUint32 program, WTF::CheckedInt32 location, WTF::CheckedUint64 valueSize, CompletionHandler<void(std::span<const uint32_t>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    if (!WTF::isValidCapacityForVector<GCGLuint>(valueSize))
        valueSize = 4;
    Vector<GCGLuint, 4> value(FillWith { }, valueSize, 0);
    protect(m_context)->getUniformuiv(program, location, value);
    completionHandler(spanReinterpretCast<const uint32_t>(value.span()));
}

void RemoteGraphicsContextGL::getVertexAttribOffset(WTF::CheckedUint32 index, WTF::CheckedUint32 pname, CompletionHandler<void(uint64_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLsizeiptr returnValue = { };
    returnValue = protect(m_context)->getVertexAttribOffset(index, pname);
    completionHandler(static_cast<uint64_t>(returnValue));
}

void RemoteGraphicsContextGL::hint(WTF::CheckedUint32 target, WTF::CheckedUint32 mode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->hint(target, mode);
}

void RemoteGraphicsContextGL::isBuffer(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isBuffer(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::isEnabled(WTF::CheckedUint32 cap, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    returnValue = protect(m_context)->isEnabled(cap);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::isFramebuffer(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isFramebuffer(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::isProgram(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isProgram(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::isRenderbuffer(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isRenderbuffer(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::isShader(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isShader(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::isTexture(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isTexture(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::lineWidth(float arg0)
{
    assertIsCurrent(workQueue());
    protect(m_context)->lineWidth(arg0);
}

void RemoteGraphicsContextGL::linkProgram(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->linkProgram(arg0);
}

void RemoteGraphicsContextGL::pixelStorei(WTF::CheckedUint32 pname, WTF::CheckedInt32 param)
{
    assertIsCurrent(workQueue());
    protect(m_context)->pixelStorei(pname, param);
}

void RemoteGraphicsContextGL::polygonOffset(float factor, float units)
{
    assertIsCurrent(workQueue());
    protect(m_context)->polygonOffset(factor, units);
}

void RemoteGraphicsContextGL::renderbufferStorage(WTF::CheckedUint32 target, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->renderbufferStorage(target, internalformat, width, height);
}

void RemoteGraphicsContextGL::sampleCoverage(float value, bool invert)
{
    assertIsCurrent(workQueue());
    protect(m_context)->sampleCoverage(value, static_cast<GCGLboolean>(invert));
}

void RemoteGraphicsContextGL::scissor(WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->scissor(x, y, width, height);
}

void RemoteGraphicsContextGL::shaderSource(WTF::CheckedUint32 arg0, CString&& arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->shaderSource(arg0, arg1);
}

void RemoteGraphicsContextGL::stencilFunc(WTF::CheckedUint32 func, WTF::CheckedInt32 ref, WTF::CheckedUint32 mask)
{
    assertIsCurrent(workQueue());
    protect(m_context)->stencilFunc(func, ref, mask);
}

void RemoteGraphicsContextGL::stencilFuncSeparate(WTF::CheckedUint32 face, WTF::CheckedUint32 func, WTF::CheckedInt32 ref, WTF::CheckedUint32 mask)
{
    assertIsCurrent(workQueue());
    protect(m_context)->stencilFuncSeparate(face, func, ref, mask);
}

void RemoteGraphicsContextGL::stencilMask(WTF::CheckedUint32 mask)
{
    assertIsCurrent(workQueue());
    protect(m_context)->stencilMask(mask);
}

void RemoteGraphicsContextGL::stencilMaskSeparate(WTF::CheckedUint32 face, WTF::CheckedUint32 mask)
{
    assertIsCurrent(workQueue());
    protect(m_context)->stencilMaskSeparate(face, mask);
}

void RemoteGraphicsContextGL::stencilOp(WTF::CheckedUint32 fail, WTF::CheckedUint32 zfail, WTF::CheckedUint32 zpass)
{
    assertIsCurrent(workQueue());
    protect(m_context)->stencilOp(fail, zfail, zpass);
}

void RemoteGraphicsContextGL::stencilOpSeparate(WTF::CheckedUint32 face, WTF::CheckedUint32 fail, WTF::CheckedUint32 zfail, WTF::CheckedUint32 zpass)
{
    assertIsCurrent(workQueue());
    protect(m_context)->stencilOpSeparate(face, fail, zfail, zpass);
}

void RemoteGraphicsContextGL::texParameterf(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, float param)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texParameterf(target, pname, param);
}

void RemoteGraphicsContextGL::texParameteri(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, WTF::CheckedInt32 param)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texParameteri(target, pname, param);
}

void RemoteGraphicsContextGL::uniform1f(WTF::CheckedInt32 location, float x)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform1f(location, x);
}

void RemoteGraphicsContextGL::uniform1fv(WTF::CheckedInt32 location, std::span<const float>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform1fv(location, v);
}

void RemoteGraphicsContextGL::uniform1i(WTF::CheckedInt32 location, WTF::CheckedInt32 x)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform1i(location, x);
}

void RemoteGraphicsContextGL::uniform1iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform1iv(location, v);
}

void RemoteGraphicsContextGL::uniform2f(WTF::CheckedInt32 location, float x, float y)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform2f(location, x, y);
}

void RemoteGraphicsContextGL::uniform2fv(WTF::CheckedInt32 location, std::span<const float>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform2fv(location, v);
}

void RemoteGraphicsContextGL::uniform2i(WTF::CheckedInt32 location, WTF::CheckedInt32 x, WTF::CheckedInt32 y)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform2i(location, x, y);
}

void RemoteGraphicsContextGL::uniform2iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform2iv(location, v);
}

void RemoteGraphicsContextGL::uniform3f(WTF::CheckedInt32 location, float x, float y, float z)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform3f(location, x, y, z);
}

void RemoteGraphicsContextGL::uniform3fv(WTF::CheckedInt32 location, std::span<const float>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform3fv(location, v);
}

void RemoteGraphicsContextGL::uniform3i(WTF::CheckedInt32 location, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 z)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform3i(location, x, y, z);
}

void RemoteGraphicsContextGL::uniform3iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform3iv(location, v);
}

void RemoteGraphicsContextGL::uniform4f(WTF::CheckedInt32 location, float x, float y, float z, float w)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform4f(location, x, y, z, w);
}

void RemoteGraphicsContextGL::uniform4fv(WTF::CheckedInt32 location, std::span<const float>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform4fv(location, v);
}

void RemoteGraphicsContextGL::uniform4i(WTF::CheckedInt32 location, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 z, WTF::CheckedInt32 w)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform4i(location, x, y, z, w);
}

void RemoteGraphicsContextGL::uniform4iv(WTF::CheckedInt32 location, std::span<const int32_t>&& v)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform4iv(location, v);
}

void RemoteGraphicsContextGL::uniformMatrix2fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& value)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix2fv(location, static_cast<GCGLboolean>(transpose), value);
}

void RemoteGraphicsContextGL::uniformMatrix3fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& value)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix3fv(location, static_cast<GCGLboolean>(transpose), value);
}

void RemoteGraphicsContextGL::uniformMatrix4fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& value)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix4fv(location, static_cast<GCGLboolean>(transpose), value);
}

void RemoteGraphicsContextGL::useProgram(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->useProgram(arg0);
}

void RemoteGraphicsContextGL::validateProgram(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->validateProgram(arg0);
}

void RemoteGraphicsContextGL::vertexAttrib1f(WTF::CheckedUint32 index, float x)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib1f(index, x);
}

void RemoteGraphicsContextGL::vertexAttrib1fv(WTF::CheckedUint32 index, std::span<const float, 1>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib1fv(index, values);
}

void RemoteGraphicsContextGL::vertexAttrib2f(WTF::CheckedUint32 index, float x, float y)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib2f(index, x, y);
}

void RemoteGraphicsContextGL::vertexAttrib2fv(WTF::CheckedUint32 index, std::span<const float, 2>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib2fv(index, values);
}

void RemoteGraphicsContextGL::vertexAttrib3f(WTF::CheckedUint32 index, float x, float y, float z)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib3f(index, x, y, z);
}

void RemoteGraphicsContextGL::vertexAttrib3fv(WTF::CheckedUint32 index, std::span<const float, 3>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib3fv(index, values);
}

void RemoteGraphicsContextGL::vertexAttrib4f(WTF::CheckedUint32 index, float x, float y, float z, float w)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib4f(index, x, y, z, w);
}

void RemoteGraphicsContextGL::vertexAttrib4fv(WTF::CheckedUint32 index, std::span<const float, 4>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttrib4fv(index, values);
}

void RemoteGraphicsContextGL::vertexAttribPointer(WTF::CheckedUint32 index, WTF::CheckedInt32 size, WTF::CheckedUint32 type, bool normalized, WTF::CheckedInt32 stride, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribPointer(index, size, type, static_cast<GCGLboolean>(normalized), stride, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::viewport(WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->viewport(x, y, width, height);
}

void RemoteGraphicsContextGL::bufferData0(WTF::CheckedUint32 target, WTF::CheckedUint64 arg1, WTF::CheckedUint32 usage)
{
    assertIsCurrent(workQueue());
    protect(m_context)->bufferData(target, static_cast<GCGLsizeiptr>(arg1), usage);
}

void RemoteGraphicsContextGL::bufferData1(WTF::CheckedUint32 target, std::span<const uint8_t>&& data, WTF::CheckedUint32 usage)
{
    assertIsCurrent(workQueue());
    protect(m_context)->bufferData(target, data, usage);
}

void RemoteGraphicsContextGL::bufferSubData(WTF::CheckedUint32 target, WTF::CheckedUint64 offset, std::span<const uint8_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->bufferSubData(target, static_cast<GCGLintptr>(offset), data);
}

void RemoteGraphicsContextGL::readPixelsBufferObject(WebCore::IntRect&& arg0, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset, WTF::CheckedInt32 alignment, WTF::CheckedInt32 rowLength)
{
    assertIsCurrent(workQueue());
    protect(m_context)->readPixelsBufferObject(arg0, format, type, static_cast<GCGLintptr>(offset), alignment, rowLength);
}

void RemoteGraphicsContextGL::texImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texImage2D(target, level, internalformat, width, height, border, format, type, pixels);
}

void RemoteGraphicsContextGL::texImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texImage2D(target, level, internalformat, width, height, border, format, type, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::texSubImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels);
}

void RemoteGraphicsContextGL::texSubImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texSubImage2D(target, level, xoffset, yoffset, width, height, format, type, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::compressedTexImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, std::span<const uint8_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexImage2D(target, level, internalformat, width, height, border, data);
}

void RemoteGraphicsContextGL::compressedTexImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 border, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexImage2D(target, level, internalformat, width, height, border, imageSize, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::compressedTexSubImage2D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, std::span<const uint8_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, data);
}

void RemoteGraphicsContextGL::compressedTexSubImage2D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedUint32 format, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::drawArraysInstanced(WTF::CheckedUint32 mode, WTF::CheckedInt32 first, WTF::CheckedInt32 count, WTF::CheckedInt32 primcount)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawArraysInstanced(mode, first, count, primcount);
}

void RemoteGraphicsContextGL::drawElementsInstanced(WTF::CheckedUint32 mode, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset, WTF::CheckedInt32 primcount)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawElementsInstanced(mode, count, type, static_cast<GCGLintptr>(offset), primcount);
}

void RemoteGraphicsContextGL::vertexAttribDivisor(WTF::CheckedUint32 index, WTF::CheckedUint32 divisor)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribDivisor(index, divisor);
}

void RemoteGraphicsContextGL::createVertexArray(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createVertexArray();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteVertexArray(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteVertexArray(arg0);
}

void RemoteGraphicsContextGL::isVertexArray(WTF::CheckedUint32 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->isVertexArray(arg0);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::bindVertexArray(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->bindVertexArray(arg0);
}

void RemoteGraphicsContextGL::copyBufferSubData(WTF::CheckedUint32 readTarget, WTF::CheckedUint32 writeTarget, WTF::CheckedUint64 readOffset, WTF::CheckedUint64 writeOffset, WTF::CheckedUint64 arg4)
{
    assertIsCurrent(workQueue());
    protect(m_context)->copyBufferSubData(readTarget, writeTarget, static_cast<GCGLintptr>(readOffset), static_cast<GCGLintptr>(writeOffset), static_cast<GCGLsizeiptr>(arg4));
}

void RemoteGraphicsContextGL::blitFramebuffer(WTF::CheckedInt32 srcX0, WTF::CheckedInt32 srcY0, WTF::CheckedInt32 srcX1, WTF::CheckedInt32 srcY1, WTF::CheckedInt32 dstX0, WTF::CheckedInt32 dstY0, WTF::CheckedInt32 dstX1, WTF::CheckedInt32 dstY1, WTF::CheckedUint32 mask, WTF::CheckedUint32 filter)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blitFramebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter);
}

void RemoteGraphicsContextGL::framebufferTextureLayer(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 texture, WTF::CheckedInt32 level, WTF::CheckedInt32 layer)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(texture));
    if (texture)
        texture = m_objectNames.get(texture);
    protect(m_context)->framebufferTextureLayer(target, attachment, texture, level, layer);
}

void RemoteGraphicsContextGL::readBuffer(WTF::CheckedUint32 src)
{
    assertIsCurrent(workQueue());
    protect(m_context)->readBuffer(src);
}

void RemoteGraphicsContextGL::renderbufferStorageMultisample(WTF::CheckedUint32 target, WTF::CheckedInt32 samples, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->renderbufferStorageMultisample(target, samples, internalformat, width, height);
}

void RemoteGraphicsContextGL::texStorage2D(WTF::CheckedUint32 target, WTF::CheckedInt32 levels, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texStorage2D(target, levels, internalformat, width, height);
}

void RemoteGraphicsContextGL::texStorage3D(WTF::CheckedUint32 target, WTF::CheckedInt32 levels, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texStorage3D(target, levels, internalformat, width, height, depth);
}

void RemoteGraphicsContextGL::texImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texImage3D(target, level, internalformat, width, height, depth, border, format, type, pixels);
}

void RemoteGraphicsContextGL::texImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texImage3D(target, level, internalformat, width, height, depth, border, format, type, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::texSubImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, WTF::CheckedUint32 type, std::span<const uint8_t>&& pixels)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels);
}

void RemoteGraphicsContextGL::texSubImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, WTF::CheckedUint32 type, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->texSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::copyTexSubImage3D(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->copyTexSubImage3D(target, level, xoffset, yoffset, zoffset, x, y, width, height);
}

void RemoteGraphicsContextGL::compressedTexImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, std::span<const uint8_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexImage3D(target, level, internalformat, width, height, depth, border, data);
}

void RemoteGraphicsContextGL::compressedTexImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedInt32 border, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexImage3D(target, level, internalformat, width, height, depth, border, imageSize, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::compressedTexSubImage3D0(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, std::span<const uint8_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, data);
}

void RemoteGraphicsContextGL::compressedTexSubImage3D1(WTF::CheckedUint32 target, WTF::CheckedInt32 level, WTF::CheckedInt32 xoffset, WTF::CheckedInt32 yoffset, WTF::CheckedInt32 zoffset, WTF::CheckedInt32 width, WTF::CheckedInt32 height, WTF::CheckedInt32 depth, WTF::CheckedUint32 format, WTF::CheckedInt32 imageSize, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->compressedTexSubImage3D(target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::getFragDataLocation(WTF::CheckedUint32 program, CString&& name, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->getFragDataLocation(program, name);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::uniform1ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform1ui(location, v0);
}

void RemoteGraphicsContextGL::uniform2ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0, WTF::CheckedUint32 v1)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform2ui(location, v0, v1);
}

void RemoteGraphicsContextGL::uniform3ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0, WTF::CheckedUint32 v1, WTF::CheckedUint32 v2)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform3ui(location, v0, v1, v2);
}

void RemoteGraphicsContextGL::uniform4ui(WTF::CheckedInt32 location, WTF::CheckedUint32 v0, WTF::CheckedUint32 v1, WTF::CheckedUint32 v2, WTF::CheckedUint32 v3)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform4ui(location, v0, v1, v2, v3);
}

void RemoteGraphicsContextGL::uniform1uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform1uiv(location, data);
}

void RemoteGraphicsContextGL::uniform2uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform2uiv(location, data);
}

void RemoteGraphicsContextGL::uniform3uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform3uiv(location, data);
}

void RemoteGraphicsContextGL::uniform4uiv(WTF::CheckedInt32 location, std::span<const uint32_t>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniform4uiv(location, data);
}

void RemoteGraphicsContextGL::uniformMatrix2x3fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix2x3fv(location, static_cast<GCGLboolean>(transpose), data);
}

void RemoteGraphicsContextGL::uniformMatrix3x2fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix3x2fv(location, static_cast<GCGLboolean>(transpose), data);
}

void RemoteGraphicsContextGL::uniformMatrix2x4fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix2x4fv(location, static_cast<GCGLboolean>(transpose), data);
}

void RemoteGraphicsContextGL::uniformMatrix4x2fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix4x2fv(location, static_cast<GCGLboolean>(transpose), data);
}

void RemoteGraphicsContextGL::uniformMatrix3x4fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix3x4fv(location, static_cast<GCGLboolean>(transpose), data);
}

void RemoteGraphicsContextGL::uniformMatrix4x3fv(WTF::CheckedInt32 location, bool transpose, std::span<const float>&& data)
{
    assertIsCurrent(workQueue());
    protect(m_context)->uniformMatrix4x3fv(location, static_cast<GCGLboolean>(transpose), data);
}

void RemoteGraphicsContextGL::vertexAttribI4i(WTF::CheckedUint32 index, WTF::CheckedInt32 x, WTF::CheckedInt32 y, WTF::CheckedInt32 z, WTF::CheckedInt32 w)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribI4i(index, x, y, z, w);
}

void RemoteGraphicsContextGL::vertexAttribI4iv(WTF::CheckedUint32 index, std::span<const int32_t, 4>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribI4iv(index, values);
}

void RemoteGraphicsContextGL::vertexAttribI4ui(WTF::CheckedUint32 index, WTF::CheckedUint32 x, WTF::CheckedUint32 y, WTF::CheckedUint32 z, WTF::CheckedUint32 w)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribI4ui(index, x, y, z, w);
}

void RemoteGraphicsContextGL::vertexAttribI4uiv(WTF::CheckedUint32 index, std::span<const uint32_t, 4>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribI4uiv(index, values);
}

void RemoteGraphicsContextGL::vertexAttribIPointer(WTF::CheckedUint32 index, WTF::CheckedInt32 size, WTF::CheckedUint32 type, WTF::CheckedInt32 stride, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->vertexAttribIPointer(index, size, type, stride, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::drawRangeElements(WTF::CheckedUint32 mode, WTF::CheckedUint32 start, WTF::CheckedUint32 end, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawRangeElements(mode, start, end, count, type, static_cast<GCGLintptr>(offset));
}

void RemoteGraphicsContextGL::clearBufferiv(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, std::span<const int32_t>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearBufferiv(buffer, drawbuffer, values);
}

void RemoteGraphicsContextGL::clearBufferuiv(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, std::span<const uint32_t>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearBufferuiv(buffer, drawbuffer, values);
}

void RemoteGraphicsContextGL::clearBufferfv(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, std::span<const float>&& values)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearBufferfv(buffer, drawbuffer, values);
}

void RemoteGraphicsContextGL::clearBufferfi(WTF::CheckedUint32 buffer, WTF::CheckedInt32 drawbuffer, float depth, WTF::CheckedInt32 stencil)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clearBufferfi(buffer, drawbuffer, depth, stencil);
}

void RemoteGraphicsContextGL::createQuery(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createQuery();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteQuery(WTF::CheckedUint32 query)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (!query) [[unlikely]]
        return;
    query = m_objectNames.take(query);
    protect(m_context)->deleteQuery(query);
}

void RemoteGraphicsContextGL::isQuery(WTF::CheckedUint32 query, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    returnValue = protect(m_context)->isQuery(query);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::beginQuery(WTF::CheckedUint32 target, WTF::CheckedUint32 query)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    protect(m_context)->beginQuery(target, query);
}

void RemoteGraphicsContextGL::endQuery(WTF::CheckedUint32 target)
{
    assertIsCurrent(workQueue());
    protect(m_context)->endQuery(target);
}

void RemoteGraphicsContextGL::getQuery(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getQuery(target, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getQueryObjectui(WTF::CheckedUint32 query, WTF::CheckedUint32 pname, CompletionHandler<void(uint32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLuint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    returnValue = protect(m_context)->getQueryObjectui(query, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::createSampler(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createSampler();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteSampler(WTF::CheckedUint32 sampler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (!sampler) [[unlikely]]
        return;
    sampler = m_objectNames.take(sampler);
    protect(m_context)->deleteSampler(sampler);
}

void RemoteGraphicsContextGL::isSampler(WTF::CheckedUint32 sampler, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (sampler)
        sampler = m_objectNames.get(sampler);
    returnValue = protect(m_context)->isSampler(sampler);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::bindSampler(WTF::CheckedUint32 unit, WTF::CheckedUint32 sampler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (sampler)
        sampler = m_objectNames.get(sampler);
    protect(m_context)->bindSampler(unit, sampler);
}

void RemoteGraphicsContextGL::samplerParameteri(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, WTF::CheckedInt32 param)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (sampler)
        sampler = m_objectNames.get(sampler);
    protect(m_context)->samplerParameteri(sampler, pname, param);
}

void RemoteGraphicsContextGL::samplerParameterf(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, float param)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (sampler)
        sampler = m_objectNames.get(sampler);
    protect(m_context)->samplerParameterf(sampler, pname, param);
}

void RemoteGraphicsContextGL::getSamplerParameterf(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, CompletionHandler<void(float)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLfloat returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (sampler)
        sampler = m_objectNames.get(sampler);
    returnValue = protect(m_context)->getSamplerParameterf(sampler, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getSamplerParameteri(WTF::CheckedUint32 sampler, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(sampler));
    if (sampler)
        sampler = m_objectNames.get(sampler);
    returnValue = protect(m_context)->getSamplerParameteri(sampler, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::fenceSync(WTF::CheckedUint32 condition, WTF::CheckedUint32 flags, CompletionHandler<void(uint64_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLsync returnValue = { };
    returnValue = protect(m_context)->fenceSync(condition, flags);
    completionHandler(static_cast<uint64_t>(reinterpret_cast<intptr_t>(returnValue)));
}

void RemoteGraphicsContextGL::isSync(WTF::CheckedUint64 arg0, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    returnValue = protect(m_context)->isSync(reinterpret_cast<GCGLsync>(static_cast<intptr_t>(arg0)));
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::deleteSync(WTF::CheckedUint64 arg0)
{
    assertIsCurrent(workQueue());
    protect(m_context)->deleteSync(reinterpret_cast<GCGLsync>(static_cast<intptr_t>(arg0)));
}

void RemoteGraphicsContextGL::clientWaitSync(WTF::CheckedUint64 arg0, WTF::CheckedUint32 flags, WTF::CheckedUint64 timeout, CompletionHandler<void(uint32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLenum returnValue = { };
    returnValue = protect(m_context)->clientWaitSync(reinterpret_cast<GCGLsync>(static_cast<intptr_t>(arg0)), flags, static_cast<GCGLuint64>(timeout));
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::waitSync(WTF::CheckedUint64 arg0, WTF::CheckedUint32 flags, WTF::CheckedInt64 timeout)
{
    assertIsCurrent(workQueue());
    protect(m_context)->waitSync(reinterpret_cast<GCGLsync>(static_cast<intptr_t>(arg0)), flags, static_cast<GCGLint64>(timeout));
}

void RemoteGraphicsContextGL::getSynci(WTF::CheckedUint64 arg0, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getSynci(reinterpret_cast<GCGLsync>(static_cast<intptr_t>(arg0)), pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::createTransformFeedback(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createTransformFeedback();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteTransformFeedback(WTF::CheckedUint32 id)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(id));
    if (!id) [[unlikely]]
        return;
    id = m_objectNames.take(id);
    protect(m_context)->deleteTransformFeedback(id);
}

void RemoteGraphicsContextGL::isTransformFeedback(WTF::CheckedUint32 id, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(id));
    if (id)
        id = m_objectNames.get(id);
    returnValue = protect(m_context)->isTransformFeedback(id);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::bindTransformFeedback(WTF::CheckedUint32 target, WTF::CheckedUint32 id)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(id));
    if (id)
        id = m_objectNames.get(id);
    protect(m_context)->bindTransformFeedback(target, id);
}

void RemoteGraphicsContextGL::beginTransformFeedback(WTF::CheckedUint32 primitiveMode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->beginTransformFeedback(primitiveMode);
}

void RemoteGraphicsContextGL::endTransformFeedback()
{
    assertIsCurrent(workQueue());
    protect(m_context)->endTransformFeedback();
}

void RemoteGraphicsContextGL::transformFeedbackVaryings(WTF::CheckedUint32 program, Vector<CString>&& varyings, WTF::CheckedUint32 bufferMode)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    protect(m_context)->transformFeedbackVaryings(program, varyings, bufferMode);
}

void RemoteGraphicsContextGL::getTransformFeedbackVarying(WTF::CheckedUint32 program, WTF::CheckedUint32 index, CompletionHandler<void(std::optional<WebCore::GCGLTransformFeedbackActiveInfo>&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    std::optional<WebCore::GCGLTransformFeedbackActiveInfo> returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->getTransformFeedbackVarying(program, index);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::pauseTransformFeedback()
{
    assertIsCurrent(workQueue());
    protect(m_context)->pauseTransformFeedback();
}

void RemoteGraphicsContextGL::resumeTransformFeedback()
{
    assertIsCurrent(workQueue());
    protect(m_context)->resumeTransformFeedback();
}

void RemoteGraphicsContextGL::bindBufferBase(WTF::CheckedUint32 target, WTF::CheckedUint32 index, WTF::CheckedUint32 buffer)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(buffer));
    if (buffer)
        buffer = m_objectNames.get(buffer);
    protect(m_context)->bindBufferBase(target, index, buffer);
}

void RemoteGraphicsContextGL::bindBufferRange(WTF::CheckedUint32 target, WTF::CheckedUint32 index, WTF::CheckedUint32 buffer, WTF::CheckedUint64 offset, WTF::CheckedUint64 arg4)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(buffer));
    if (buffer)
        buffer = m_objectNames.get(buffer);
    protect(m_context)->bindBufferRange(target, index, buffer, static_cast<GCGLintptr>(offset), static_cast<GCGLsizeiptr>(arg4));
}

void RemoteGraphicsContextGL::getUniformBlockIndex(WTF::CheckedUint32 program, CString&& uniformBlockName, CompletionHandler<void(uint32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLuint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->getUniformBlockIndex(program, uniformBlockName);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getActiveUniformBlockName(WTF::CheckedUint32 program, WTF::CheckedUint32 uniformBlockIndex, CompletionHandler<void(CString&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    CString returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    returnValue = protect(m_context)->getActiveUniformBlockName(program, uniformBlockIndex);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::uniformBlockBinding(WTF::CheckedUint32 program, WTF::CheckedUint32 uniformBlockIndex, WTF::CheckedUint32 uniformBlockBinding)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    protect(m_context)->uniformBlockBinding(program, uniformBlockIndex, uniformBlockBinding);
}

void RemoteGraphicsContextGL::getActiveUniformBlockiv(WTF::CheckedUint32 program, WTF::CheckedUint32 uniformBlockIndex, WTF::CheckedUint32 pname, WTF::CheckedUint64 paramsSize, CompletionHandler<void(std::span<const int32_t>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(program));
    if (program)
        program = m_objectNames.get(program);
    if (!WTF::isValidCapacityForVector<GCGLint>(paramsSize))
        paramsSize = 4;
    Vector<GCGLint, 4> params(FillWith { }, paramsSize, 0);
    protect(m_context)->getActiveUniformBlockiv(program, uniformBlockIndex, pname, params);
    completionHandler(spanReinterpretCast<const int32_t>(params.span()));
}

void RemoteGraphicsContextGL::getTranslatedShaderSourceANGLE(WTF::CheckedUint32 arg0, CompletionHandler<void(CString&&)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    CString returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    returnValue = protect(m_context)->getTranslatedShaderSourceANGLE(arg0);
    completionHandler(WTF::move(returnValue));
}

void RemoteGraphicsContextGL::createQueryEXT(WTF::CheckedUint32 name)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createQueryEXT();
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteQueryEXT(WTF::CheckedUint32 query)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (!query) [[unlikely]]
        return;
    query = m_objectNames.take(query);
    protect(m_context)->deleteQueryEXT(query);
}

void RemoteGraphicsContextGL::isQueryEXT(WTF::CheckedUint32 query, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLboolean returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    returnValue = protect(m_context)->isQueryEXT(query);
    completionHandler(static_cast<bool>(returnValue));
}

void RemoteGraphicsContextGL::beginQueryEXT(WTF::CheckedUint32 target, WTF::CheckedUint32 query)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    protect(m_context)->beginQueryEXT(target, query);
}

void RemoteGraphicsContextGL::endQueryEXT(WTF::CheckedUint32 target)
{
    assertIsCurrent(workQueue());
    protect(m_context)->endQueryEXT(target);
}

void RemoteGraphicsContextGL::queryCounterEXT(WTF::CheckedUint32 query, WTF::CheckedUint32 target)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    protect(m_context)->queryCounterEXT(query, target);
}

void RemoteGraphicsContextGL::getQueryiEXT(WTF::CheckedUint32 target, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    returnValue = protect(m_context)->getQueryiEXT(target, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getQueryObjectiEXT(WTF::CheckedUint32 query, WTF::CheckedUint32 pname, CompletionHandler<void(int32_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    returnValue = protect(m_context)->getQueryObjectiEXT(query, pname);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::getQueryObjectui64EXT(WTF::CheckedUint32 query, WTF::CheckedUint32 pname, CompletionHandler<void(uint64_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLuint64 returnValue = { };
    MESSAGE_CHECK(m_objectNames.isValidKey(query));
    if (query)
        query = m_objectNames.get(query);
    returnValue = protect(m_context)->getQueryObjectui64EXT(query, pname);
    completionHandler(static_cast<uint64_t>(returnValue));
}

void RemoteGraphicsContextGL::getInteger64EXT(WTF::CheckedUint32 pname, CompletionHandler<void(int64_t)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    GCGLint64 returnValue = { };
    returnValue = protect(m_context)->getInteger64EXT(pname);
    completionHandler(static_cast<int64_t>(returnValue));
}

void RemoteGraphicsContextGL::enableiOES(WTF::CheckedUint32 target, WTF::CheckedUint32 index)
{
    assertIsCurrent(workQueue());
    protect(m_context)->enableiOES(target, index);
}

void RemoteGraphicsContextGL::disableiOES(WTF::CheckedUint32 target, WTF::CheckedUint32 index)
{
    assertIsCurrent(workQueue());
    protect(m_context)->disableiOES(target, index);
}

void RemoteGraphicsContextGL::blendEquationiOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 mode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendEquationiOES(buf, mode);
}

void RemoteGraphicsContextGL::blendEquationSeparateiOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 modeRGB, WTF::CheckedUint32 modeAlpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendEquationSeparateiOES(buf, modeRGB, modeAlpha);
}

void RemoteGraphicsContextGL::blendFunciOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 src, WTF::CheckedUint32 dst)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendFunciOES(buf, src, dst);
}

void RemoteGraphicsContextGL::blendFuncSeparateiOES(WTF::CheckedUint32 buf, WTF::CheckedUint32 srcRGB, WTF::CheckedUint32 dstRGB, WTF::CheckedUint32 srcAlpha, WTF::CheckedUint32 dstAlpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->blendFuncSeparateiOES(buf, srcRGB, dstRGB, srcAlpha, dstAlpha);
}

void RemoteGraphicsContextGL::colorMaskiOES(WTF::CheckedUint32 buf, bool red, bool green, bool blue, bool alpha)
{
    assertIsCurrent(workQueue());
    protect(m_context)->colorMaskiOES(buf, static_cast<GCGLboolean>(red), static_cast<GCGLboolean>(green), static_cast<GCGLboolean>(blue), static_cast<GCGLboolean>(alpha));
}

void RemoteGraphicsContextGL::drawArraysInstancedBaseInstanceANGLE(WTF::CheckedUint32 mode, WTF::CheckedInt32 first, WTF::CheckedInt32 count, WTF::CheckedInt32 instanceCount, WTF::CheckedUint32 baseInstance)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawArraysInstancedBaseInstanceANGLE(mode, first, count, instanceCount, baseInstance);
}

void RemoteGraphicsContextGL::drawElementsInstancedBaseVertexBaseInstanceANGLE(WTF::CheckedUint32 mode, WTF::CheckedInt32 count, WTF::CheckedUint32 type, WTF::CheckedUint64 offset, WTF::CheckedInt32 instanceCount, WTF::CheckedInt32 baseVertex, WTF::CheckedUint32 baseInstance)
{
    assertIsCurrent(workQueue());
    protect(m_context)->drawElementsInstancedBaseVertexBaseInstanceANGLE(mode, count, type, static_cast<GCGLintptr>(offset), instanceCount, baseVertex, baseInstance);
}

void RemoteGraphicsContextGL::clipControlEXT(WTF::CheckedUint32 origin, WTF::CheckedUint32 depth)
{
    assertIsCurrent(workQueue());
    protect(m_context)->clipControlEXT(origin, depth);
}

void RemoteGraphicsContextGL::provokingVertexANGLE(WTF::CheckedUint32 provokeMode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->provokingVertexANGLE(provokeMode);
}

void RemoteGraphicsContextGL::polygonModeANGLE(WTF::CheckedUint32 face, WTF::CheckedUint32 mode)
{
    assertIsCurrent(workQueue());
    protect(m_context)->polygonModeANGLE(face, mode);
}

void RemoteGraphicsContextGL::polygonOffsetClampEXT(float factor, float units, float clamp)
{
    assertIsCurrent(workQueue());
    protect(m_context)->polygonOffsetClampEXT(factor, units, clamp);
}

void RemoteGraphicsContextGL::renderbufferStorageMultisampleANGLE(WTF::CheckedUint32 target, WTF::CheckedInt32 samples, WTF::CheckedUint32 internalformat, WTF::CheckedInt32 width, WTF::CheckedInt32 height)
{
    assertIsCurrent(workQueue());
    protect(m_context)->renderbufferStorageMultisampleANGLE(target, samples, internalformat, width, height);
}

void RemoteGraphicsContextGL::getInternalformativ(WTF::CheckedUint32 target, WTF::CheckedUint32 internalformat, WTF::CheckedUint32 pname, WTF::CheckedUint64 paramsSize, CompletionHandler<void(std::span<const int32_t>)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    if (!WTF::isValidCapacityForVector<GCGLint>(paramsSize))
        paramsSize = 4;
    Vector<GCGLint, 4> params(FillWith { }, paramsSize, 0);
    protect(m_context)->getInternalformativ(target, internalformat, pname, params);
    completionHandler(spanReinterpretCast<const int32_t>(params.span()));
}

#if ENABLE(WEBXR)
void RemoteGraphicsContextGL::createExternalImage(WTF::CheckedUint32 name, WebCore::GraphicsContextGL::ExternalImageSource&& arg0, WTF::CheckedUint32 internalFormat, WTF::CheckedInt32 layer)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createExternalImage(WTF::move(arg0), internalFormat, layer);
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteExternalImage(WTF::CheckedUint32 handle)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(handle));
    if (!handle) [[unlikely]]
        return;
    handle = m_objectNames.take(handle);
    protect(m_context)->deleteExternalImage(handle);
}

void RemoteGraphicsContextGL::bindExternalImage(WTF::CheckedUint32 target, WTF::CheckedUint32 arg1)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg1));
    if (arg1)
        arg1 = m_objectNames.get(arg1);
    protect(m_context)->bindExternalImage(target, arg1);
}

void RemoteGraphicsContextGL::createExternalSync(WTF::CheckedUint32 name, WebCore::GraphicsContextGL::ExternalSyncSource&& arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(name));
    auto result = protect(m_context)->createExternalSync(WTF::move(arg0));
    if (result)
        m_objectNames.add(name, result);
}

void RemoteGraphicsContextGL::deleteExternalSync(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (!arg0) [[unlikely]]
        return;
    arg0 = m_objectNames.take(arg0);
    protect(m_context)->deleteExternalSync(arg0);
}

void RemoteGraphicsContextGL::enableRequiredWebXRExtensions(CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXREnabled());
    bool returnValue = { };
    returnValue = protect(m_context)->enableRequiredWebXRExtensions();
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::addFoveation(WebCore::IntSize&& physicalSizeLeft, WebCore::IntSize&& physicalSizeRight, WebCore::IntSize&& screenSize, std::span<const float>&& horizontalSamplesLeft, std::span<const float>&& verticalSamples, std::span<const float>&& horizontalSamplesRight, CompletionHandler<void(bool)>&& completionHandler)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    bool returnValue = { };
    returnValue = protect(m_context)->addFoveation(physicalSizeLeft, physicalSizeRight, screenSize, horizontalSamplesLeft, verticalSamples, horizontalSamplesRight);
    completionHandler(returnValue);
}

void RemoteGraphicsContextGL::enableFoveation(WTF::CheckedUint32 arg0)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg0));
    if (arg0)
        arg0 = m_objectNames.get(arg0);
    protect(m_context)->enableFoveation(arg0);
}

void RemoteGraphicsContextGL::disableFoveation()
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    protect(m_context)->disableFoveation();
}

void RemoteGraphicsContextGL::framebufferResolveRenderbuffer(WTF::CheckedUint32 target, WTF::CheckedUint32 attachment, WTF::CheckedUint32 renderbuffertarget, WTF::CheckedUint32 arg3)
{
    assertIsCurrent(workQueue());
    MESSAGE_CHECK(webXRPromptAccepted());
    MESSAGE_CHECK(m_objectNames.isValidKey(arg3));
    if (arg3)
        arg3 = m_objectNames.get(arg3);
    protect(m_context)->framebufferResolveRenderbuffer(target, attachment, renderbuffertarget, arg3);
}

#endif

}

#undef MESSAGE_CHECK
#endif
