module-name = 'bmalloc'
requirements = ['cplusplus11']

[module.bexport]
attributes = ['extern_c']
headers = ['BExport.h']

[module.pas_allocation_mode]
attributes = ['extern_c']
headers = ['pas_allocation_mode.h']
