// This file is automatically generated from CSSProperties.json by the process-css-properties.py script. Do not edit it.

#ifndef WebCore_css_scripts_test_TestCSSPropertiesResults_StylePropertyShorthandFunctions_h
#define WebCore_css_scripts_test_TestCSSPropertiesResults_StylePropertyShorthandFunctions_h

namespace WebCore {

class StylePropertyShorthand;

StylePropertyShorthand fontShorthand();
StylePropertyShorthand testShorthandOneShorthand();
StylePropertyShorthand testShorthandTwoShorthand();

} // namespace WebCore

#endif // WebCore_css_scripts_test_TestCSSPropertiesResults_StylePropertyShorthandFunctions_h
